import {gql} from '@apollo/client';

export const getUser = gql`
  query GetUser($id: ID!) {
    getUser(id: $id) {
      id
      name
      email
      phone_number
      accountStatus
      enableNotificationOrders
      enableNotificationPromotions
      enableNotificationRFF
      enableNotificationRFQ
      enableNotificationSellOffer
      rating
      accountType
      lastOnlineAt
      lat
      lng
      ledgerBalance
      address
      city
      state
      zipCode
      lga
      website
      incorporateDate
      rcNumber
      totalOrders
      level
      identification
      identificationNumber
      identityDocs
      keyProduct
      country
      inviteCode
      title
      logo
      backgroundImage
      images
      businessType
      certifications
      certsDoc
      mainMarkets
      memberShipType
      sellerLevel
      estRevenue
      totalStaff
      responseTime
      languages
      legalRep
      overview
      activeOrder
      Orders {
        items {
          id
          createdAt
          SType
          requestID
          orderType
          orderStatus
          totalAmount
          orderDate
          paidThrough
          paymentResponse
          userID
          updatedAt
          __typename
        }
        nextToken
        __typename
      }
      Products {
        items {
          id
          createdAt
          SType
          productID
          title
          productImage
          image
          images
          description
          productSpec
          rating
          tags
          productCert
          landmark
          supplyCapacity
          unit
          minOrderQty
          packageType
          quantity
          noOfReviews
          transportMode
          placeOrigin
          dateAvailable
          productDocs
          productCertDocs
          category
          commodityCategory
          userID
          Reviews {
            nextToken
            __typename
          }
          updatedAt
          __typename
        }
        nextToken
        __typename
      }
      Reviews {
        items {
          id
          createdAt
          SType
          name
          rating
          comment
          forUserID
          userID
          productID
          updatedAt
          __typename
        }
        nextToken
        __typename
      }
      RFQS {
        items {
          id
          createdAt
          SType
          rfqNo
          rfqType
          title
          requestCategory
          description
          documents
          productName
          tags
          qty
          buyFrequency
          budget
          placeOrigin
          placeOriginFlag
          placeOriginName
          placeOriginCountry
          landmark
          unit
          incoterms
          placeDestinationName
          placeDestination
          placeDestinationFlag
          destinationCountry
          deliveryPeriod
          expiryDate
          paymentType
          paymentMethod
          userID
          RFQReplies {
            nextToken
            __typename
          }
          updatedAt
          __typename
        }
        nextToken
        __typename
      }
      RFFS {
        items {
          id
          createdAt
          SType
          rffNo
          rffType
          deliveryPeriod
          requestCategory
          rffRequestType
          productName
          handling
          budget
          loadDate
          weight
          qty
          length
          width
          height
          packageType
          placeOrigin
          placeOriginFlag
          placeOriginName
          placeOriginCountry
          placeDestinationName
          placeDestinationFlag
          destinationCountry
          placeDestination
          relatedServices
          document
          notes
          containerDetails
          containerSize
          containerType
          requestType
          userID
          RFFReplies {
            nextToken
            __typename
          }
          updatedAt
          __typename
        }
        nextToken
        __typename
      }
      SellOffers {
        items {
          id
          createdAt
          SType
          sellOfferID
          requestCategory
          title
          tags
          productName
          description
          packageDesc
          sellOfferImage
          image
          images
          rfqType
          packageType
          placeOrigin
          landmark
          unit
          deliveryDate
          qtyMeasure
          basePrice
          fobPrice
          paymentType
          paymentMethod
          offerValidity
          forUserID
          agreement
          userID
          SellOfferReplies {
            nextToken
            __typename
          }
          updatedAt
          __typename
        }
        nextToken
        __typename
      }
      Wishlists {
        items {
          id
          createdAt
          SType
          productImage
          title
          serviceType
          supplyCapacity
          minOrderQty
          productID
          product {
            id
            createdAt
            SType
            productID
            title
            productImage
            image
            images
            description
            productSpec
            rating
            tags
            productCert
            landmark
            supplyCapacity
            unit
            minOrderQty
            packageType
            quantity
            noOfReviews
            transportMode
            placeOrigin
            dateAvailable
            productDocs
            productCertDocs
            category
            commodityCategory
            userID
            updatedAt
            __typename
          }
          userID
          updatedAt
          wishlistProductId
          __typename
        }
        nextToken
        __typename
      }
      Messages {
        items {
          text
          createdAt
          readAt
          SType
          rffID
          rfqID
          rfqType
          rffType
          sellOfferID
          productID
          requestID
          requestTitle
          requestQty
          packageType
          unit
          description
          serviceType
          requestPrice
          serviceImage
          requestFrom
          requestFromImg
          requestTo
          requestToImg
          status
          image
          file
          replyToMessageID
          title
          forUserID
          userID
          chatroomID
          id
          updatedAt
          __typename
        }
        nextToken
        __typename
      }
      ChatRooms {
        items {
          id
          chatRoomId
          userId
          chatRoom {
            id
            createdAt
            SType
            name
            imageUri
            updatedAt
            chatRoomLastMessageId
            __typename
          }
          user {
            id
            name
            email
            phone_number
            accountStatus
            enableNotificationOrders
            enableNotificationPromotions
            enableNotificationRFF
            enableNotificationRFQ
            enableNotificationSellOffer
            rating
            accountType
            lastOnlineAt
            lat
            lng
            ledgerBalance
            address
            city
            state
            zipCode
            lga
            website
            incorporateDate
            rcNumber
            totalOrders
            level
            identification
            identificationNumber
            identityDocs
            keyProduct
            country
            inviteCode
            title
            logo
            backgroundImage
            images
            businessType
            certifications
            certsDoc
            mainMarkets
            memberShipType
            sellerLevel
            estRevenue
            totalStaff
            responseTime
            languages
            legalRep
            overview
            activeOrder
            fcmToken
            createdAt
            updatedAt
            __typename
          }
          createdAt
          updatedAt
          __typename
        }
        nextToken
        __typename
      }
      fcmToken
      Notifications {
        items {
          id
          createdAt
          SType
          type
          readAt
          title
          description
          requestType
          chatroomID
          userID
          User {
            id
            name
            email
            phone_number
            accountStatus
            enableNotificationOrders
            enableNotificationPromotions
            enableNotificationRFF
            enableNotificationRFQ
            enableNotificationSellOffer
            rating
            accountType
            lastOnlineAt
            lat
            lng
            ledgerBalance
            address
            city
            state
            zipCode
            lga
            website
            incorporateDate
            rcNumber
            totalOrders
            level
            identification
            identificationNumber
            identityDocs
            keyProduct
            country
            inviteCode
            title
            logo
            backgroundImage
            images
            businessType
            certifications
            certsDoc
            mainMarkets
            memberShipType
            sellerLevel
            estRevenue
            totalStaff
            responseTime
            languages
            legalRep
            overview
            activeOrder
            fcmToken
            createdAt
            updatedAt
            __typename
          }
          actorID
          Actor {
            id
            name
            email
            phone_number
            accountStatus
            enableNotificationOrders
            enableNotificationPromotions
            enableNotificationRFF
            enableNotificationRFQ
            enableNotificationSellOffer
            rating
            accountType
            lastOnlineAt
            lat
            lng
            ledgerBalance
            address
            city
            state
            zipCode
            lga
            website
            incorporateDate
            rcNumber
            totalOrders
            level
            identification
            identificationNumber
            identityDocs
            keyProduct
            country
            inviteCode
            title
            logo
            backgroundImage
            images
            businessType
            certifications
            certsDoc
            mainMarkets
            memberShipType
            sellerLevel
            estRevenue
            totalStaff
            responseTime
            languages
            legalRep
            overview
            activeOrder
            fcmToken
            createdAt
            updatedAt
            __typename
          }
          SellOffer {
            id
            createdAt
            SType
            sellOfferID
            requestCategory
            title
            tags
            productName
            description
            packageDesc
            sellOfferImage
            image
            images
            rfqType
            packageType
            placeOrigin
            landmark
            unit
            deliveryDate
            qtyMeasure
            basePrice
            fobPrice
            paymentType
            paymentMethod
            offerValidity
            forUserID
            agreement
            userID
            updatedAt
            __typename
          }
          SellOfferReply {
            id
            createdAt
            SType
            requestCategory
            title
            tags
            productName
            description
            packageDesc
            sellOfferID
            sellOfferImage
            image
            images
            rfqType
            packageType
            placeOrigin
            landmark
            unit
            deliveryDate
            qtyMeasure
            basePrice
            fobPrice
            paymentType
            paymentMethod
            offerValidity
            forUserID
            userID
            agreement
            SellOffer
            updatedAt
            __typename
          }
          RFF {
            id
            createdAt
            SType
            rffNo
            rffType
            deliveryPeriod
            requestCategory
            rffRequestType
            productName
            handling
            budget
            loadDate
            weight
            qty
            length
            width
            height
            packageType
            placeOrigin
            placeOriginFlag
            placeOriginName
            placeOriginCountry
            placeDestinationName
            placeDestinationFlag
            destinationCountry
            placeDestination
            relatedServices
            document
            notes
            containerDetails
            containerSize
            containerType
            requestType
            userID
            updatedAt
            __typename
          }
          RFFReply {
            id
            createdAt
            SType
            rffNo
            rffType
            deliveryPeriod
            requestCategory
            rffRequestType
            productName
            handling
            budget
            price
            loadDate
            weight
            qty
            length
            width
            height
            packageType
            placeOrigin
            placeOriginFlag
            placeOriginName
            placeOriginCountry
            placeDestinationName
            placeDestinationFlag
            paymentType
            paymentMethod
            destinationCountry
            placeDestination
            relatedServices
            document
            notes
            unit
            containerDetails
            containerSize
            containerType
            requestType
            forUserID
            userID
            statusText
            agreement
            RFF
            updatedAt
            __typename
          }
          RFQ {
            id
            createdAt
            SType
            rfqNo
            rfqType
            title
            requestCategory
            description
            documents
            productName
            tags
            qty
            buyFrequency
            budget
            placeOrigin
            placeOriginFlag
            placeOriginName
            placeOriginCountry
            landmark
            unit
            incoterms
            placeDestinationName
            placeDestination
            placeDestinationFlag
            destinationCountry
            deliveryPeriod
            expiryDate
            paymentType
            paymentMethod
            userID
            updatedAt
            __typename
          }
          RFQReply {
            id
            createdAt
            SType
            rfqNo
            rfqType
            title
            requestCategory
            description
            documents
            productName
            tags
            qty
            buyFrequency
            budget
            price
            placeOrigin
            placeOriginFlag
            placeOriginName
            landmark
            unit
            incoterms
            placeDestinationName
            placeOriginCountry
            placeDestination
            placeDestinationFlag
            destinationCountry
            deliveryPeriod
            expiryDate
            paymentType
            paymentMethod
            forUserID
            userID
            statusText
            agreement
            RFQ
            updatedAt
            __typename
          }
          Product {
            id
            createdAt
            SType
            productID
            title
            productImage
            image
            images
            description
            productSpec
            rating
            tags
            productCert
            landmark
            supplyCapacity
            unit
            minOrderQty
            packageType
            quantity
            noOfReviews
            transportMode
            placeOrigin
            dateAvailable
            productDocs
            productCertDocs
            category
            commodityCategory
            userID
            updatedAt
            __typename
          }
          Order {
            id
            createdAt
            SType
            requestID
            orderType
            orderStatus
            totalAmount
            orderDate
            paidThrough
            paymentResponse
            userID
            updatedAt
            __typename
          }
          updatedAt
          notificationSellOfferId
          notificationSellOfferReplyId
          notificationRFFId
          notificationRFFReplyId
          notificationRFQId
          notificationRFQReplyId
          notificationProductId
          notificationOrderId
          __typename
        }
        nextToken
        __typename
      }
      createdAt
      updatedAt
      __typename
    }
  }
`;

export const listUsers = gql`
  query ListUsers(
    $filter: ModelUserFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listUsers(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        name
        email
        phone_number
        accountStatus
        enableNotificationOrders
        enableNotificationPromotions
        enableNotificationRFF
        enableNotificationRFQ
        enableNotificationSellOffer
        rating
        accountType
        lastOnlineAt
        lat
        lng
        ledgerBalance
        address
        city
        state
        zipCode
        lga
        website
        incorporateDate
        rcNumber
        totalOrders
        level
        identification
        identificationNumber
        identityDocs
        keyProduct
        country
        inviteCode
        title
        logo
        backgroundImage
        images
        businessType
        certifications
        certsDoc
        mainMarkets
        memberShipType
        sellerLevel
        estRevenue
        totalStaff
        responseTime
        languages
        legalRep
        overview
        activeOrder
        Orders {
          items {
            id
            createdAt
            SType
            requestID
            orderType
            orderStatus
            totalAmount
            orderDate
            paidThrough
            paymentResponse
            userID
            updatedAt
            __typename
          }
          nextToken
          __typename
        }
        Products {
          items {
            id
            createdAt
            SType
            productID
            title
            productImage
            image
            images
            description
            productSpec
            rating
            tags
            productCert
            landmark
            supplyCapacity
            unit
            minOrderQty
            packageType
            quantity
            noOfReviews
            transportMode
            placeOrigin
            dateAvailable
            productDocs
            productCertDocs
            category
            commodityCategory
            userID
            updatedAt
            __typename
          }
          nextToken
          __typename
        }
        Reviews {
          items {
            id
            createdAt
            SType
            name
            rating
            comment
            forUserID
            userID
            productID
            updatedAt
            __typename
          }
          nextToken
          __typename
        }
        RFQS {
          items {
            id
            createdAt
            SType
            rfqNo
            rfqType
            title
            requestCategory
            description
            documents
            productName
            tags
            qty
            buyFrequency
            budget
            placeOrigin
            placeOriginFlag
            placeOriginName
            placeOriginCountry
            landmark
            unit
            incoterms
            placeDestinationName
            placeDestination
            placeDestinationFlag
            destinationCountry
            deliveryPeriod
            expiryDate
            paymentType
            paymentMethod
            userID
            updatedAt
            __typename
          }
          nextToken
          __typename
        }
        RFFS {
          items {
            id
            createdAt
            SType
            rffNo
            rffType
            deliveryPeriod
            requestCategory
            rffRequestType
            productName
            handling
            budget
            loadDate
            weight
            qty
            length
            width
            height
            packageType
            placeOrigin
            placeOriginFlag
            placeOriginName
            placeOriginCountry
            placeDestinationName
            placeDestinationFlag
            destinationCountry
            placeDestination
            relatedServices
            document
            notes
            containerDetails
            containerSize
            containerType
            requestType
            userID
            updatedAt
            __typename
          }
          nextToken
          __typename
        }
        SellOffers {
          items {
            id
            createdAt
            SType
            sellOfferID
            requestCategory
            title
            tags
            productName
            description
            packageDesc
            sellOfferImage
            image
            images
            rfqType
            packageType
            placeOrigin
            landmark
            unit
            deliveryDate
            qtyMeasure
            basePrice
            fobPrice
            paymentType
            paymentMethod
            offerValidity
            forUserID
            agreement
            userID
            updatedAt
            __typename
          }
          nextToken
          __typename
        }
        Wishlists {
          items {
            id
            createdAt
            SType
            productImage
            title
            serviceType
            supplyCapacity
            minOrderQty
            productID
            userID
            updatedAt
            wishlistProductId
            __typename
          }
          nextToken
          __typename
        }
        Messages {
          items {
            text
            createdAt
            readAt
            SType
            rffID
            rfqID
            rfqType
            rffType
            sellOfferID
            productID
            requestID
            requestTitle
            requestQty
            packageType
            unit
            description
            serviceType
            requestPrice
            serviceImage
            requestFrom
            requestFromImg
            requestTo
            requestToImg
            status
            image
            file
            replyToMessageID
            title
            forUserID
            userID
            chatroomID
            id
            updatedAt
            __typename
          }
          nextToken
          __typename
        }
        ChatRooms {
          items {
            id
            chatRoomId
            userId
            createdAt
            updatedAt
            __typename
          }
          nextToken
          __typename
        }
        fcmToken
        Notifications {
          items {
            id
            createdAt
            SType
            type
            readAt
            title
            description
            requestType
            chatroomID
            userID
            actorID
            updatedAt
            notificationSellOfferId
            notificationSellOfferReplyId
            notificationRFFId
            notificationRFFReplyId
            notificationRFQId
            notificationRFQReplyId
            notificationProductId
            notificationOrderId
            __typename
          }
          nextToken
          __typename
        }
        createdAt
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
  }
`;

export const updateUser = gql`
  mutation UpdateUser(
    $input: UpdateUserInput!
    $condition: ModelUserConditionInput
  ) {
    updateUser(input: $input, condition: $condition) {
      id
      name
      email
      phone_number
      accountStatus
      enableNotificationOrders
      enableNotificationPromotions
      enableNotificationRFF
      enableNotificationRFQ
      enableNotificationSellOffer
      rating
      accountType
      lastOnlineAt
      lat
      lng
      ledgerBalance
      address
      city
      state
      zipCode
      lga
      website
      incorporateDate
      rcNumber
      totalOrders
      level
      identification
      identificationNumber
      identityDocs
      keyProduct
      country
      inviteCode
      title
      logo
      backgroundImage
      images
      businessType
      certifications
      certsDoc
      mainMarkets
      memberShipType
      sellerLevel
      estRevenue
      totalStaff
      responseTime
      languages
      legalRep
      overview
      activeOrder
      fcmToken
      createdAt
      updatedAt
      __typename
    }
  }
`;

export const deleteUser = gql`
  mutation DeleteUser(
    $input: DeleteUserInput!
    $condition: ModelUserConditionInput
  ) {
    deleteUser(input: $input, condition: $condition) {
      id
    }
  }
`;

export const reviewByDate = gql`
  query ReviewByDate(
    $SType: String!
    $createdAt: ModelStringKeyConditionInput
    $sortDirection: ModelSortDirection
    $filter: ModelReviewFilterInput
    $limit: Int
    $nextToken: String
  ) {
    reviewByDate(
      SType: $SType
      createdAt: $createdAt
      sortDirection: $sortDirection
      filter: $filter
      limit: $limit
      nextToken: $nextToken
    ) {
      items {
        id
        createdAt
        SType
        name
        rating
        comment
        forUserID
        userID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
  }
`;

export const getReview = gql`
  query GetReview($id: ID!) {
    getReview(id: $id) {
      id
      createdAt
      SType
      name
      rating
      comment
      forUserID
      userID
      productID
      updatedAt
      __typename
    }
  }
`;
