import {COLORS} from './theme';

const promos = [
  {
    id: '1',
    name: 'Fresh Get connected to guaranteed seller',
    subText: 'And get 50% off,Join Now!',
    image: require('../assets/images/Ornaments.png'),
    bg_color: COLORS.primary1,
  },
  {
    id: '2',
    name: 'Get connected to guaranteed seller',
    subText: 'And get 50% off,Join Now!',
    image: require('../assets/images/Ornaments.png'),
    bg_color: COLORS.NeutralBlue1,
  },
  {
    id: '3',
    name: 'Get connected to guaranteed seller',
    subText: 'And get 50% off,Join Now!',
    image: require('../assets/images/Ornaments.png'),
    bg_color: COLORS.secondary1,
  },
];

const reviews = [
  {
    id: '1',
    rate: 4,
    user: 'Bernando Silva',
    reviews: 75,
    description:
      'Good service, very communicative seller. Provide detailed product specifications. According to what is in the description.',
    time: 'Just now',
  },
  {
    id: '2',
    rate: 3,
    user: 'Abaz Udosen',
    reviews: 124,
    description:
      'Good service, very communicative seller. Provide detailed product specifications. According to what is in the description.',
    time: 'Just now',
  },
];

const orders = [
  {
    id: 7,
    orderID: 'DJ084N1',
    to: 'Kingston, Jamaica',
    toImg: require('../assets/images/jamaica.png'),
    from: 'Seoul, South Korea',
    fromImg: require('../assets/images/south-korea.png'),
    type: 'RFF',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Waiting for Payment',
    time: '2023-02-10',
  },
  {
    id: 8,
    orderID: 'JDU290DK',
    to: 'Cairo, Egypt',
    toImg: require('../assets/images/egypt.png'),
    from: 'Abuja, Nigeria',
    fromImg: require('../assets/images/nigeria.png'),
    type: 'RFF',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Land',
    image: require('../assets/images/land.png'),
    status: 'Pending',
    time: '2023-02-20',
  },
  {
    id: 1,
    orderID: 'BC5678XX',
    to: 'Tokyo, Japan',
    toImg: require('../assets/images/japan.png'),
    from: 'Jos, Nigeria',
    fromImg: require('../assets/images/nigeria.png'),
    type: 'RFF',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'International',
    image: require('../assets/images/land.png'),
    status: 'Order Arrived',
    time: '2023-02-25',
  },
  {
    id: 2,
    orderID: 'DU1JO284',
    to: 'New York, USA',
    toImg: require('../assets/images/united-states.png'),
    from: 'Accra, Ghana',
    fromImg: require('../assets/images/ghana.png'),
    type: 'RFQ',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Air Freight',
    image: require('../assets/images/air.png'),
    status: 'Order Started',
    time: '2023-03-07',
  },
  {
    id: 3,
    orderID: 'JJD10N17',
    to: 'Beijing, China',
    toImg: require('../assets/images/china.png'),
    from: 'Cape Town, RSA',
    fromImg: require('../assets/images/south-africa.png'),
    type: 'RFF',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Ocean Freight',
    image: require('../assets/images/water.png'),
    status: 'Delivery Update',
    time: '2023-04-11',
  },
  {
    id: 4,
    orderID: 'MDJ7163S',
    to: 'Lagos, Nigeria',
    toImg: require('../assets/images/nigeria.png'),
    from: 'Ibadan, Nigeria',
    fromImg: require('../assets/images/nigeria.png'),
    type: 'RFQ',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Canceled',
    time: '2023-03-22',
  },
  {
    id: 5,
    orderID: 'NCI20CNA',
    to: 'Algiers, Algeria',
    toImg: require('../assets/images/algeria.png'),
    from: 'Kinshasa, DRC',
    fromImg: require('../assets/images/drc.png'),
    type: 'RFF',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Request for Review',
    time: '2023-05-18',
  },
  {
    id: 6,
    orderID: 'CNCO22O',
    to: 'Sao Paulo, Brazil',
    toImg: require('../assets/images/brazil.png'),
    from: 'Seoul, South Korea',
    fromImg: require('../assets/images/south-korea.png'),
    type: 'RFQ',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for atleast 1 year.',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Completed',
    time: '2023-04-13',
  },
];

const shipStatusInfo_OrderReceived = [
  {
    id: 1,
    orderType: 'International',
    orderTypeImg: require('../assets/images/international.png'),
    orderTypeDesc: 'Serving international delivery',
    name: 'Bonoze Catering Services',
    address:
      'No. 38, S.L Akintola Blvd, Garki II, Abuja, 900108, Graki 2, Federal Capital Territory, Nigeria',
  },
];

const shipStatusInfo_OrderAccepted = [
  {
    id: 1,
    orderID: 'BC5678XX',
  },
];

const shipStatusInfo_OrderStarted = [
  {
    id: 1,
    orderID: 'BC5678XX',
    info: 'Your Expected Delivery Date is 10 - 15th June, 2023',
  },
];

const shipStatusInfo_OrderArrived = [
  {
    id: 1,
    trackID: '#TRC90182YUIA',
    info: 'Your date of delivery was updated to 10 - 15th June, 2023',
  },
];

const shipStatusInfo_OrderReviewRequest = [
  {
    id: 1,
    trackID: '90182YUIA',
    info: 'You have accepted Tomato King’s request to review your order and extend the delivery date.',
    duration: '4 days',
  },
];

const shipStatusInfo_OrderComplete = [
  {
    id: 1,
    trackID: '90182YUIA',
    recipient: 'Abu Bakar',
  },
];

const shipStatusInfo_OrderCanceled = [
  {
    id: 1,
    trackID: '#TRC90182YUIA',
    info: 'Your Order was Canceled',
  },
];

const shipStatusInfo_Payment = [
  {
    id: 1,
    paymentTerm: 'Advanced Payment',
    paymentMethod: 'Citibank Nigeria Ltd.',
    paymentBankImg: require('../assets/images/international.png'),
    totalItems: 2,
    amt: 919000,
    subTotal: 150000,
    discount: 5,
    total: 10690000,
  },
];

const shipping_status = [
  {
    id: 0,
    label: 'Order Received',
    date_time: '23rd September 2023, 11:00 AM',
    info: shipStatusInfo_OrderReceived,
    detail: 'View Details',
    is_current_status: false,
  },
  {
    id: 1,
    label: 'Order Accepted',
    date_time: '23rd September 2023, 11:00 AM',
    info: shipStatusInfo_OrderAccepted,
    detail: 'View Details',
    is_current_status: false,
  },
  {
    id: 2,
    label: 'Payment',
    date_time: '23rd September 2023, 11:00 AM',
    info: shipStatusInfo_Payment,
    detail: 'View Details',
    is_current_status: false,
  },
  {
    id: 3,
    label: 'Order Started',
    date_time: '23rd September 2023, 11:00 AM',
    info: shipStatusInfo_OrderStarted,
    detail: 'View Details',
    is_current_status: true,
  },
  {
    id: 4,
    label: 'Order Arrived',
    date_time: '',
    info: shipStatusInfo_OrderArrived,
    detail: 'View Details',
    is_current_status: false,
  },
  {
    id: 5,
    label: 'Order Review Request',
    date_time: '',
    info: shipStatusInfo_OrderReviewRequest,
    detail: 'View Details',
    is_current_status: false,
  },
  {
    id: 6,
    label: 'Order Complete',
    date_time: '',
    info: shipStatusInfo_OrderComplete,
    detail: 'View Details',
    is_current_status: false,
  },
  {
    id: 6,
    label: 'Order Canceled',
    date_time: '',
    info: shipStatusInfo_OrderCanceled,
    detail: 'View Details',
    is_current_status: false,
  },
];

const shipIcons = [
  {
    id: 0,
    image: require('../assets/icons/receive.png'),
  },
  {
    id: 1,
    image: require('../assets/icons/accepted.png'),
  },
  {
    id: 2,
    image: require('../assets/icons/payment.png'),
  },
  {
    id: 3,
    image: require('../assets/icons/started.png'),
  },
  {
    id: 4,
    image: require('../assets/icons/arrive.png'),
  },
  {
    id: 5,
    image: require('../assets/icons/review.png'),
  },
  {
    id: 6,
    image: require('../assets/icons/complete.png'),
  },
];

const transactionHistory = [
  {
    id: '10CS1203',
    title: 'Topped up wallet',
    status: 'CREDIT',
    amount: 405.23,
    date: '5 February, 2023',
  },
  {
    id: '019SJL83',
    title: 'Trip deduction',
    status: 'CREDIT',
    amount: 1519.5,
    date: '5 February, 2023',
  },
  {
    id: 'AB1293KS',
    title: 'Withdraw from your account',
    status: 'DEBIT',
    amount: 7000.1,
    date: '1 March, 2023',
  },
  {
    id: '203NV270',
    title: 'Added to wallet',
    status: 'CREDIT',
    amount: 914.4,
    date: '1 March, 2023',
  },
  {
    id: 'NU71NS1',
    title: 'Withdraw from wallet',
    status: 'DEBIT',
    amount: 527.26,
    date: '1 March, 2023',
  },
  {
    id: 'JD29824H',
    title: 'Land Deposit from bank',
    status: 'DEBIT',
    amount: 1240.142,
    date: '12 April, 2023',
  },
  {
    id: 'JDJ2902S',
    title: 'Simple RFF',
    status: 'CREDIT',
    amount: 31042.41,
    date: '12 April, 2023',
  },
  {
    id: 'XJA10311',
    title: 'Bill payment',
    status: 'DEBIT',
    amount: 23901.16,
    date: '05 May, 2023',
  },
  {
    id: 'MN791SK',
    title: 'Money Transfer',
    status: 'CREDIT',
    amount: 10000.0,
    date: '05 May, 2023',
  },
  {
    id: 'U82S01A',
    title: 'Wallet credit',
    status: 'CREDIT',
    amount: 401399.26,
    date: '12 June, 2023',
  },
  {
    id: 'TEU8134D',
    title: 'Data recharge',
    status: 'DEBIT',
    amount: 5400.48,
    date: '12 June, 2023',
  },
];

const rfqItems = [
  {
    id: 1,
    rfqNo: 'BC5678XX',
    to: 'Tokyo, Japan',
    toImg: require('../assets/images/japan.png'),
    departDate: '7 April, 2024',
    arrivalDate: '14, April, 2024',
    type: 'RFQ',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'International',
    image: require('../assets/images/land.png'),
    status: 'Order Arrived',
    expiry: 15,
    expiryDate: '05 September 2023',
    productName: 'Fresh Tomatoes',
    qty: 200,
    price: 5000000,
    orderID: 'JDN82020',
    incoterms: 'Free on Board (FOB)',
    paymentTerms: 'Advance Payment',
  },
  {
    id: 2,
    rfqNo: 'DU1JO284',
    to: 'New York, USA',
    toImg: require('../assets/images/united-states.png'),
    departDate: '13 May, 2024',
    arrivalDate: '21, June, 2024',
    type: 'RFQ',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Air Freight',
    image: require('../assets/images/air.png'),
    status: 'Order Started',
    expiry: 15,
    expiryDate: '11 June 2023',
    productName: 'Apple',
    qty: 150,
    price: 5000000,
    orderID: 'ADJANV2',
    incoterms: 'Free on Board (FOB)',
    paymentTerms: 'Advance Payment',
  },
  {
    id: 3,
    rfqNo: 'JJD10N17',
    to: 'Beijing, China',
    toImg: require('../assets/images/china.png'),
    departDate: '27 February, 2024',
    arrivalDate: '14, March, 2024',
    type: 'RFQ',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Ocean Freight',
    image: require('../assets/images/water.png'),
    status: 'Delivery Update',
    expiry: 15,
    expiryDate: '19 April 2023',
    productName: 'Yams',
    qty: 350,
    price: 5000000,
    orderID: 'CNVHB52',
    incoterms: 'Free on Board (FOB)',
    paymentTerms: 'Advance Payment',
  },
];

const rffItems = [
  {
    id: 1,
    orderID: 'BC5678XX',
    to: 'Tokyo, Japan',
    toImg: require('../assets/images/japan.png'),
    departDate: '13 July, 2024',
    arrivalDate: '04, August, 2024',
    name: 'Toptal Limited',
    departAddress:
      'No. 38, S.L Akintola Blvd, Garki II, Abuja, 900108, Graki 2, Federal Capital Territory, Nigeria',
    arrivalAddress:
      'Wuse II, Abuja, AMAC, FCT. Kampala St. 900288, Wuse II, Abuja',
    from: 'Jos, Nigeria',
    fromImg: require('../assets/images/nigeria.png'),
    type: 'RFF',
    packageType: 'Box/Crate',
    transportMode: 'Land',
    relatedServices: 'Insurance, CC, IS, Cert.',
    portOrigin: 'Shangahi, China',
    portDestination: 'Lagos, Nigeria',
  },
  {
    id: 2,
    orderID: 'DU1JO284',
    to: 'New York, USA',
    departDate: '7 April, 2024',
    arrivalDate: '14, April, 2024',
    toImg: require('../assets/images/united-states.png'),
    name: 'ABC Services',
    departAddress:
      'No. 38, S.L Akintola Blvd, Garki II, Abuja, 900108, Graki 2, Federal Capital Territory, Nigeria',
    arrivalAddress:
      'Wuse II, Abuja, AMAC, FCT. Kampala St. 900288, Wuse II, Abuja',
    from: 'Accra, Ghana',
    fromImg: require('../assets/images/ghana.png'),
    type: 'RFF',
    packageType: 'Box/Crate',
    transportMode: 'Land',
    relatedServices: 'Insurance, CC, IS, Cert.',
    portOrigin: 'Shangahi, China',
    portDestination: 'Lagos, Nigeria',
  },
  {
    id: 3,
    orderID: 'JJD10N17',
    to: 'Beijing, China',
    departDate: '01 October, 2024',
    arrivalDate: '20, October, 2024',
    toImg: require('../assets/images/china.png'),
    name: 'Bonoze Catering Services',
    departAddress:
      'No. 38, S.L Akintola Blvd, Garki II, Abuja, 900108, Graki 2, Federal Capital Territory, Nigeria',
    arrivalAddress:
      'Wuse II, Abuja, AMAC, FCT. Kampala St. 900288, Wuse II, Abuja',
    from: 'Cape Town, RSA',
    fromImg: require('../assets/images/south-africa.png'),
    type: 'RFF',
    packageType: 'Box/Crate',
    transportMode: 'Air',
    relatedServices: 'Insurance, CC, IS, Cert.',
    portOrigin: 'Shangahi, China',
    portDestination: 'Lagos, Nigeria',
  },
];

const rffAgentReq = [
  {
    id: 1,
    to: 'Tokyo, Japan freight forwarder seeks agents in ',
    toImg: require('../assets/images/japan.png'),
    from: 'Jos, Nigeria',
    fromImg: require('../assets/images/nigeria.png'),
    transportMode: 'Land',
    posted: '19 April 2023',
    for: 'Co-operation',
    status: 'Live',
  },
  {
    id: 2,
    to: 'New York, USA freight forwarder seeks agents in ',
    toImg: require('../assets/images/united-states.png'),
    from: 'Accra, Ghana',
    fromImg: require('../assets/images/ghana.png'),
    transportMode: 'Land',
    posted: '19 April 2023',
    for: 'Co-operation',
    portDestination: 'Lagos, Nigeria',
  },
  {
    id: 3,
    to: 'Beijing, China freight forwarder seeks agents in',
    toImg: require('../assets/images/china.png'),
    from: 'Cape Town, RSA',
    fromImg: require('../assets/images/south-africa.png'),
    transportMode: 'Land',
    posted: '19 April 2023',
    for: 'Co-operation',
    status: 'Live',
  },
];

const sellPendingOrders = [
  {
    id: 0,
    orderID: 'JAI8824',
    to: 'Munich, Germany',
    toImg: require('../assets/images/germany.png'),
    type: 'RFQ',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'RFQ Replies Sent',
    incoterms: 'Free on Board (FOB)',
    time: '2023-04-13',
  },
  {
    id: 20,
    orderID: 'VAD892R',
    to: 'Cape Town, RSA',
    toImg: require('../assets/images/south-africa.png'),
    type: 'RFQ',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'International',
    image: require('../assets/images/air.png'),
    status: 'RFQ Replies Sent',
    incoterms: 'Free on Board (FOB)',
    time: '2023-04-13',
  },
  {
    id: 14,
    orderID: '2JVN020',
    to: 'Accra, Ghana',
    toImg: require('../assets/images/ghana.png'),
    type: 'RFF',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'RFF Replies Sent',
    incoterms: 'Free on Board (FOB)',
    time: '2023-04-13',
  },
  {
    id: 10,
    orderID: 'JAI8824',
    to: 'Abuja, Nigeria',
    toImg: require('../assets/images/nigeria.png'),
    type: 'RFF',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'RFF Replies Sent',
    incoterms: 'Free on Board (FOB)',
    time: '2023-04-13',
  },
];

const seller_orders = [
  {
    id: 10,
    orderID: 'JAI8824',
    to: 'Abuja, Nigeria',
    toImg: require('../assets/images/nigeria.png'),
    type: 'RFQ',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Order Accepted',
    time: '2023-04-13',
  },
  {
    id: 9,
    orderID: 'JAI8824',
    to: 'Mumbai, India',
    toImg: require('../assets/images/india.png'),
    type: 'RFQ',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Order Completed',
    time: '2023-04-13',
  },
  {
    id: 7,
    orderID: 'DJ084N1',
    to: 'Kingston, Jamaica',
    toImg: require('../assets/images/jamaica.png'),
    type: 'RFF',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Order Delivered',
    time: '2023-02-10',
  },
  {
    id: 8,
    orderID: 'JDU290DK',
    to: 'Cairo, Egypt',
    toImg: require('../assets/images/egypt.png'),
    type: 'RFF',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Land',
    image: require('../assets/images/land.png'),
    status: 'Buyer Requested for Review',
    time: '2023-02-20',
  },
  {
    id: 1,
    orderID: 'BC5678XX',
    to: 'Tokyo, Japan',
    toImg: require('../assets/images/japan.png'),
    type: 'RFF',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'International',
    image: require('../assets/images/land.png'),
    status: 'Order Canceled',
    time: '2023-02-25',
  },
  {
    id: 2,
    orderID: 'DU1JO284',
    to: 'New York, USA',
    toImg: require('../assets/images/united-states.png'),
    type: 'RFQ',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Air Freight',
    image: require('../assets/images/air.png'),
    status: 'Order Accepted',
    time: '2023-03-07',
  },
  {
    id: 3,
    orderID: 'JJD10N17',
    to: 'Beijing, China',
    toImg: require('../assets/images/china.png'),
    type: 'RFF',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Ocean Freight',
    image: require('../assets/images/water.png'),
    status: 'Order Delivered',
    time: '2023-04-11',
  },
  {
    id: 4,
    orderID: 'MDJ7163S',
    to: 'Lagos, Nigeria',
    toImg: require('../assets/images/nigeria.png'),
    from: 'Ibadan, Nigeria',
    fromImg: require('../assets/images/nigeria.png'),
    type: 'RFQ',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Order Canceled',
    time: '2023-03-22',
  },
  {
    id: 5,
    orderID: 'NCI20CNA',
    to: 'Algiers, Algeria',
    toImg: require('../assets/images/algeria.png'),
    type: 'RFF',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Buyer Requested for Review',
    time: '2023-05-18',
  },
  {
    id: 6,
    orderID: 'CNCO22O',
    to: 'Sao Paulo, Brazil',
    toImg: require('../assets/images/brazil.png'),
    type: 'RFQ',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Order Completed',
    time: '2023-04-13',
  },
];

export default {
  rffAgentReq,
  rffItems,
  rfqItems,
  shipping_status,
  transactionHistory,
  reviews,
  promos,
  orders,
  shipIcons,
  seller_orders,
  sellPendingOrders,
};
