import {COLORS} from './theme';

const myProfile = {
  id: '1',
  username: 'user1',
  fullName: 'Abubakar Kabiru',
  profile_image: require('../assets/images/profile.png'),
  email: 'joanasmith007@gmail.com',
  address: 'Alycia Carey',
  lga: 'Central Business',
  city: 'Abuja',
  state: 'FCT',
  country: 'Nigeria',
  zipCode: '42214',
  phone: '07001234567',
  IdNumber: '2HB2872G8RV',
  IdType: 'Driver License',
  password: 'cnw0oc202jc2j2',
  walletAmt: 17444.87,
  inviteCode: 'DU92HFV',
  businessType: 'Buyer',
  keyProduct: 'Vegetables, Fruits',
};

const sellerProfile = {
  id: '1',
  username: 'user2',
  fullName: 'Abaz Udosen',
  profile_image: require('../assets/images/ab.jpg'),
  email: 'abaz@gmail.com',
  address: '123 Kings Street',
  lga: 'Atai axis',
  city: 'Uyo',
  state: 'Akwa Ibom',
  country: 'Nigeria',
  zipCode: '24044',
  phone: '07001234567',
  IdNumber: '2HB2872G8RV',
  IdType: 'Driver License',
  password: 'cnw0oc202jc2j2',
  walletAmt: 2048.87,
  inviteCode: 'HH9V242',
  businessType: 'Seller',
  keyProduct: 'Grains',
};

const promos = [
  {
    id: '1',
    name: 'Fresh Get connected to guaranteed seller',
    subText: 'And get 50% off,Join Now!',
    image: require('../assets/images/Ornaments.png'),
    bg_color: COLORS.primary1,
  },
  {
    id: '2',
    name: 'Get connected to guaranteed seller',
    subText: 'And get 50% off,Join Now!',
    image: require('../assets/images/Ornaments.png'),
    bg_color: COLORS.NeutralBlue1,
  },
  {
    id: '3',
    name: 'Get connected to guaranteed seller',
    subText: 'And get 50% off,Join Now!',
    image: require('../assets/images/Ornaments.png'),
    bg_color: COLORS.secondary1,
  },
];

const storeProducts = [
  {
    id: 0,
    supplier: 'Green Food',
    name: 'Tomato Crushed Tomatoes',
    businessType: 'Wholesale',
    cert: 'SON, NAFDAC, ISO900',
    description:
      'We source out tomato products and ingredients from top producers across the globe. Our tomato product suppliers guarantee excellent manufacturing practices and quality products in strategic locations around the world such as Europe, the United States, and South America. Our specific value to your organization comes from our expertise in logistics combined with our excellent relationships with the best partners and bulk suppliers. These supply chain essentials ensure you the best quality and price value for your Sellers tomato product needs. Tomato Products Tomato Paste bulk tomato paste Wholesale tomato paste is an essential ingredient in many food product and restaurant offerings. Rich tomato flavor is key to stimulating the taste buds and accentuating the savory notes of your product.',
    overview:
      'it is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.',
    rating: 4.0,
    distance: 2.5,
    address: 'Plot 4, 611 Road, Off 7th Avenue',
    address2: 'Jos, Nigeria',
    country: 'Nigeria',
    city: 'Jos',
    qty: 'MOQ: 1 Tons (UK)',
    qtyOffered: 140,
    paymentType: 'Advanced Payment',
    deliveryDuration: 20,
    sample: 'Available, sample cost by supplier',
    expiry: '14, April, 2024',
    expiryDays: 14,
    supplyAbility: '25000 Tonnes/week',
    minOrder: '15 Tonnes',
    price: 3000000,
    usdPrice: 3000,
    latitude: 4.92805,
    longitude: 8.32705,
    languages: [
      {
        id: 1,
        lang: 'Swahili',
      },
      {
        id: 2,
        lang: 'Hausa',
      },
      {
        id: 3,
        lang: 'English',
      },
    ],
    mainMarket: [
      {
        id: 1,
        country: 'Africa',
      },
      {
        id: 2,
        country: 'Europe',
      },
      {
        id: 3,
        country: 'Asia',
      },
    ],
    estRevenue: 390000000,
    totalStaff: 300,
    responseTime: '1 hour',
    ordersCompleted: 410,
    storeImg: require('../assets/images/res6.png'),
    storeBanner: require('../assets/images/store1.jpg'),
    img: [
      {
        id: '1',
        image: require('../assets/images/apples.jpg'),
      },
      {
        id: '2',
        image: require('../assets/images/guava.jpg'),
      },
      {
        id: '3',
        image: require('../assets/images/oranges.jpg'),
      },
    ],
    image: require('../assets/images/tomatoes.png'),
    categories: [
      {
        id: 0,
        label: 'Nuts',
        images: require('../assets/images/nuts.png'),
        items: [
          {
            id: 0,
            name: 'Pineapple',
            description: 'Mexican tortilla & tacos',
            rating: 3.5,
            price: 8140,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/apple.png'),
          },
          {
            id: 1,
            name: 'Apples',
            description: 'labore et dolore magna aliqua. Ut enim ad',
            price: 159,
            qty: 6,
            image: require('../assets/images/tomatoes.png'),
          },
        ],
      },
      {
        id: 1,
        label: 'Beans',
        images: require('../assets/images/bean.png'),
        items: [
          {
            id: 0,
            name: 'Solec Sparks',
            description: 'tastee and iceee',
            rating: 4,
            price: 1040,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/bananas2.png'),
          },
        ],
      },
    ],
  },
  {
    id: 1,
    supplier: 'Tona P',
    name: 'Fresh Apples',
    businessType: 'Large Retail',
    cert: 'SON, NAFDAC',
    description:
      'We source out tomato products and ingredients from top producers across the globe. Our tomato product suppliers guarantee excellent manufacturing practices and quality products in strategic locations around the world such as Europe, the United States, and South America. Our specific value to your organization comes from our expertise in logistics combined with our excellent relationships with the best partners and bulk suppliers. These supply chain essentials ensure you the best quality and price value for your Sellers tomato product needs. Tomato Products Tomato Paste bulk tomato paste Wholesale tomato paste is an essential ingredient in many food product and restaurant offerings. Rich tomato flavor is key to stimulating the taste buds and accentuating the savory notes of your product.',
    overview:
      'it is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.',
    rating: 4.5,
    distance: 4,
    country: 'Ghana',
    city: 'Kumasi',
    address: 'Plot 4, 611 Road, Off 7th Avenue',
    address2: 'Kumasi, Ghana',
    qty: 'MOQ: 1 Tons (UK)',
    qtyOffered: 100,
    deliveryDuration: 30,
    sample: 'Available, sample cost by supplier',
    expiry: '8, June, 2024',
    expiryDays: 21,
    paymentType: 'Advanced Payment',
    supplyAbility: '15000 Tonnes/week',
    minOrder: '5 Tonnes',
    price: 1000000,
    usdPrice: 10000,
    latitude: 4.92805,
    longitude: 8.32705,
    languages: [
      {
        id: 1,
        lang: 'Swahili',
      },
      {
        id: 2,
        lang: 'Hausa',
      },
      {
        id: 3,
        lang: 'English',
      },
    ],
    mainMarket: [
      {
        id: 1,
        country: 'Africa',
      },
      {
        id: 2,
        country: 'Europe',
      },
    ],
    estRevenue: 40000000,
    totalStaff: 130,
    responseTime: '40 Minutes',
    ordersCompleted: 40,
    storeImg: require('../assets/images/res1.png'),
    storeBanner: require('../assets/images/store2.jpg'),
    img: [
      {
        id: '0',
        image: require('../assets/images/apples.jpg'),
      },
      {
        id: '1',
        image: require('../assets/images/guava.jpg'),
      },
      {
        id: '2',
        image: require('../assets/images/oranges.jpg'),
      },
    ],
    image: require('../assets/images/apple.png'),
    categories: [
      {
        id: 0,
        label: 'Nuts',
        images: require('../assets/images/nuts.png'),
        items: [
          {
            id: 0,
            name: 'Pineapple',
            description: 'Mexican tortilla & tacos',
            rating: 3.5,
            price: 3000,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/apple.png'),
          },
          {
            id: 1,
            name: 'Apples',
            description: 'labore et dolore magna aliqua. Ut enim ad',
            price: 1500,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/Oil.png'),
          },
        ],
      },
      {
        id: 1,
        label: 'Beans',
        images: require('../assets/images/bean.png'),
        items: [
          {
            id: 0,
            name: 'Solec Sparks',
            description: 'tastee and iceee',
            rating: 4,
            price: 4400,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/bananas2.png'),
          },
        ],
      },
    ],
  },
];

const stores = [
  {
    id: 0,
    supplier: 'Green Food',
    name: 'Tomato Paste, Diced Tomatoes, Crushed Tomatoes',
    description:
      'We source out tomato products and ingredients from top producers across the globe. Our tomato product suppliers guarantee excellent manufacturing practices and quality products in strategic locations around the world such as Europe, the United States, and South America. Our specific value to your organization comes from our expertise in logistics combined with our excellent relationships with the best partners and bulk suppliers. These supply chain essentials ensure you the best quality and price value for your Sellers tomato product needs. Tomato Products Tomato Paste bulk tomato paste Wholesale tomato paste is an essential ingredient in many food product and restaurant offerings. Rich tomato flavor is key to stimulating the taste buds and accentuating the savory notes of your product.',
    rating: 4.0,
    distance: 2.5,
    address: 'Plot 4, 611 Road, Off 7th Avenue',
    address2: 'Jos, Nigeria',
    qty: 'MOQ: 1 Tons (UK)',
    latitude: 4.92805,
    longitude: 8.32705,
    image: require('../assets/images/res1.png'),
    categories: [
      {
        id: 0,
        label: 'Nuts',
        images: require('../assets/images/nuts.png'),
        items: [
          {
            id: 0,
            name: 'Pineapple',
            description: 'Mexican tortilla & tacos',
            rating: 3.5,
            price: 8140,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/apple.png'),
          },
          {
            id: 1,
            name: 'Apples',
            description: 'labore et dolore magna aliqua. Ut enim ad',
            price: 159,
            qty: 6,
            image: require('../assets/images/tomatoes.png'),
          },
        ],
      },
      {
        id: 1,
        label: 'Beans',
        images: require('../assets/images/bean.png'),
        items: [
          {
            id: 0,
            name: 'Solec Sparks',
            description: 'tastee and iceee',
            rating: 4,
            price: 1040,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/bananas2.png'),
          },
        ],
      },
    ],
  },
  {
    id: 1,
    supplier: 'Green Food',
    name: 'Fresh Apples',
    description:
      'We source out tomato products and ingredients from top producers across the globe. Our tomato product suppliers guarantee excellent manufacturing practices and quality products in strategic locations around the world such as Europe, the United States, and South America. Our specific value to your organization comes from our expertise in logistics combined with our excellent relationships with the best partners and bulk suppliers. These supply chain essentials ensure you the best quality and price value for your Sellers tomato product needs. Tomato Products Tomato Paste bulk tomato paste Wholesale tomato paste is an essential ingredient in many food product and restaurant offerings. Rich tomato flavor is key to stimulating the taste buds and accentuating the savory notes of your product.',
    rating: 4.5,
    distance: 3.5,
    address: 'Plot 4, 611 Road, Off 7th Avenue',
    address2: 'Abuja, Nigeria',
    qty: 'MOQ: 1 Tons (UK)',
    latitude: 4.92805,
    longitude: 8.32705,
    image: require('../assets/images/res2.png'),
    categories: [
      {
        id: 0,
        label: 'Nuts',
        images: require('../assets/images/nuts.png'),
        items: [
          {
            id: 0,
            name: 'Pineapple',
            description: 'Mexican tortilla & tacos',
            rating: 3.5,
            price: 3000,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/apple.png'),
          },
          {
            id: 1,
            name: 'Apples',
            description: 'labore et dolore magna aliqua. Ut enim ad',
            price: 1500,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/Oil.png'),
          },
        ],
      },
      {
        id: 1,
        label: 'Beans',
        images: require('../assets/images/bean.png'),
        items: [
          {
            id: 0,
            name: 'Solec Sparks',
            description: 'tastee and iceee',
            rating: 4,
            price: 4400,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/bananas2.png'),
          },
        ],
      },
    ],
  },
  {
    id: 2,
    supplier: 'Lakay Business',
    name: 'Fresh Grains',
    description:
      'We source out tomato products and ingredients from top producers across the globe. Our tomato product suppliers guarantee excellent manufacturing practices and quality products in strategic locations around the world such as Europe, the United States, and South America. Our specific value to your organization comes from our expertise in logistics combined with our excellent relationships with the best partners and bulk suppliers. These supply chain essentials ensure you the best quality and price value for your Sellers tomato product needs. Tomato Products Tomato Paste bulk tomato paste Wholesale tomato paste is an essential ingredient in many food product and restaurant offerings. Rich tomato flavor is key to stimulating the taste buds and accentuating the savory notes of your product.',
    rating: 4,
    address: 'Plot 4, 611 Road, Off 7th Avenue',
    address2: 'Lagos, Nigeria',
    qty: 'MOQ: 1 Tons (UK)',
    latitude: 4.96805,
    longitude: 8.38705,
    image: require('../assets/images/res6.png'),
    categories: [
      {
        id: 0,
        label: 'Nuts',
        images: require('../assets/images/nuts.png'),
        items: [
          {
            id: 0,
            name: 'Pineapple',
            description: 'Mexican tortilla & tacos',
            rating: 3.5,
            price: 3000,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/apple.png'),
          },
          {
            id: 1,
            name: 'Apples',
            description: 'labore et dolore magna aliqua. Ut enim ad',
            price: 1500,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/Oil.png'),
          },
        ],
      },
      {
        id: 1,
        label: 'Beans',
        images: require('../assets/images/bean.png'),
        items: [
          {
            id: 0,
            name: 'Solec Sparks',
            description: 'tastee and iceee',
            rating: 4,
            price: 4400,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/bananas2.png'),
          },
        ],
      },
    ],
  },
  {
    id: 3,
    supplier: 'T-Minus Grocery',
    name: 'Genu Farms',
    description:
      'We source out tomato products and ingredients from top producers across the globe. Our tomato product suppliers guarantee excellent manufacturing practices and quality products in strategic locations around the world such as Europe, the United States, and South America. Our specific value to your organization comes from our expertise in logistics combined with our excellent relationships with the best partners and bulk suppliers. These supply chain essentials ensure you the best quality and price value for your Sellers tomato product needs. Tomato Products Tomato Paste bulk tomato paste Wholesale tomato paste is an essential ingredient in many food product and restaurant offerings. Rich tomato flavor is key to stimulating the taste buds and accentuating the savory notes of your product.',
    rating: 4.5,
    address: 'Plot 4, 611 Road, Off 7th Avenue',
    address2: 'Lagos, Nigeria',
    qty: 'MOQ: 1 Tons (UK)',
    latitude: 4.42076,
    longitude: 8.58931,
    image: require('../assets/images/air.png'),
    categories: [
      {
        id: 0,
        label: 'Nuts',
        images: require('../assets/images/nuts.png'),
        items: [
          {
            id: 0,
            name: 'Pineapple',
            description: 'Mexican tortilla & tacos',
            rating: 3.5,
            price: 3000,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/apple.png'),
          },
          {
            id: 1,
            name: 'Apples',
            description: 'labore et dolore magna aliqua. Ut enim ad',
            price: 1500,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/Oil.png'),
          },
        ],
      },
      {
        id: 1,
        label: 'Beans',
        images: require('../assets/images/bean.png'),
        items: [
          {
            id: 0,
            name: 'Solec Sparks',
            description: 'tastee and iceee',
            rating: 4,
            price: 4400,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/bananas2.png'),
          },
        ],
      },
    ],
  },
  {
    id: 4,
    supplier: 'Abu Produce',
    name: 'Tek Trade',
    description:
      'We source out tomato products and ingredients from top producers across the globe. Our tomato product suppliers guarantee excellent manufacturing practices and quality products in strategic locations around the world such as Europe, the United States, and South America. Our specific value to your organization comes from our expertise in logistics combined with our excellent relationships with the best partners and bulk suppliers. These supply chain essentials ensure you the best quality and price value for your Sellers tomato product needs. Tomato Products Tomato Paste bulk tomato paste Wholesale tomato paste is an essential ingredient in many food product and restaurant offerings. Rich tomato flavor is key to stimulating the taste buds and accentuating the savory notes of your product.',
    rating: 4.7,
    address: 'Plot 4, 611 Road, Off 7th Avenue',
    address2: 'Jos, Nigeria',
    qty: 'MOQ: 1 Tons (UK)',
    latitude: 4.579294,
    longitude: 8.285291,
    image: require('../assets/images/land.png'),
    categories: [
      {
        id: 0,
        label: 'Nuts',
        images: require('../assets/images/nuts.png'),
        items: [
          {
            id: 0,
            name: 'Pineapple',
            description: 'Mexican tortilla & tacos',
            rating: 3.5,
            price: 3000,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/apple.png'),
          },
          {
            id: 1,
            name: 'Apples',
            description: 'labore et dolore magna aliqua. Ut enim ad',
            price: 1500,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/Oil.png'),
          },
        ],
      },
      {
        id: 1,
        label: 'Beans',
        images: require('../assets/images/bean.png'),
        items: [
          {
            id: 0,
            name: 'Solec Sparks',
            description: 'tastee and iceee',
            rating: 4,
            price: 4400,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/bananas2.png'),
          },
        ],
      },
    ],
  },
  {
    id: 5,
    supplier: 'Abaz Inc',
    name: 'AfroComs',
    description:
      'We source out tomato products and ingredients from top producers across the globe. Our tomato product suppliers guarantee excellent manufacturing practices and quality products in strategic locations around the world such as Europe, the United States, and South America. Our specific value to your organization comes from our expertise in logistics combined with our excellent relationships with the best partners and bulk suppliers. These supply chain essentials ensure you the best quality and price value for your Sellers tomato product needs. Tomato Products Tomato Paste bulk tomato paste Wholesale tomato paste is an essential ingredient in many food product and restaurant offerings. Rich tomato flavor is key to stimulating the taste buds and accentuating the savory notes of your product.',
    rating: 4.1,
    address: 'Plot 4, 611 Road, Off 7th Avenue',
    address2: 'Calabar, Nigeria',
    qty: 'MOQ: 1 Tons (UK)',
    latitude: 4.2513,
    longitude: 8.35192,
    image: require('../assets/images/water.png'),
    categories: [
      {
        id: 0,
        label: 'Nuts',
        images: require('../assets/images/nuts.png'),
        items: [
          {
            id: 0,
            name: 'Pineapple',
            description: 'Mexican tortilla & tacos',
            rating: 3.5,
            price: 3000,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/apple.png'),
          },
          {
            id: 1,
            name: 'Apples',
            description: 'labore et dolore magna aliqua. Ut enim ad',
            price: 1500,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/Oil.png'),
          },
        ],
      },
      {
        id: 1,
        label: 'Beans',
        images: require('../assets/images/bean.png'),
        items: [
          {
            id: 0,
            name: 'Solec Sparks',
            description: 'tastee and iceee',
            rating: 4,
            price: 4400,
            qty: 'MOQ: 1 Tons (UK)',
            image: require('../assets/images/bananas2.png'),
          },
        ],
      },
    ],
  },
];

const notifications = [
  {
    id: '1',
    title: 'New Year Eve',
    description:
      'choose anything you want to return from your favorite stores.',
    time: '2023-01-15',
  },
  {
    id: '2',
    title: 'Order Completed',
    description: 'Check your recent orders.',
    time: '2023-02-20',
  },
  {
    id: '3',
    title: 'Maintenance Update',
    description:
      'Have someone do you you the honor of returning you your precious items more important money with a click of a button.',
    time: '2023-02-25',
  },
  {
    id: '4',
    title: 'Return it Day! 👏',
    description:
      'payment made easy through debit card, credit card & more way to reimburse you.',
    time: '2023-03-07',
  },
  {
    id: '5',
    title: 'Trade Alerts',
    description: 'Tomato King is looking for posted RFQ...',
    time: '2023-04-11',
  },
];

const reviews = [
  {
    id: '1',
    rate: 4,
    user: 'Bernando Silva',
    reviews: 75,
    description:
      'Good service, very communicative seller. Provide detailed product specifications. According to what is in the description.',
    time: 'Just now',
  },
  {
    id: '2',
    rate: 3,
    user: 'Abaz Udosen',
    reviews: 124,
    description:
      'Good service, very communicative seller. Provide detailed product specifications. According to what is in the description.',
    time: 'Just now',
  },
];

const orders = [
  {
    id: 7,
    orderID: 'DJ084N1',
    to: 'Kingston, Jamaica',
    toImg: require('../assets/images/jamaica.png'),
    from: 'Seoul, South Korea',
    fromImg: require('../assets/images/south-korea.png'),
    type: 'RFF',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Waiting for Payment',
    time: '2023-02-10',
  },
  {
    id: 8,
    orderID: 'JDU290DK',
    to: 'Cairo, Egypt',
    toImg: require('../assets/images/egypt.png'),
    from: 'Abuja, Nigeria',
    fromImg: require('../assets/images/nigeria.png'),
    type: 'RFF',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Land',
    image: require('../assets/images/land.png'),
    status: 'Pending',
    time: '2023-02-20',
  },
  {
    id: 1,
    orderID: 'BC5678XX',
    to: 'Tokyo, Japan',
    toImg: require('../assets/images/japan.png'),
    from: 'Jos, Nigeria',
    fromImg: require('../assets/images/nigeria.png'),
    type: 'RFF',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'International',
    image: require('../assets/images/land.png'),
    status: 'Order Arrived',
    time: '2023-02-25',
  },
  {
    id: 2,
    orderID: 'DU1JO284',
    to: 'New York, USA',
    toImg: require('../assets/images/united-states.png'),
    from: 'Accra, Ghana',
    fromImg: require('../assets/images/ghana.png'),
    type: 'RFQ',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Air Freight',
    image: require('../assets/images/air.png'),
    status: 'Order Started',
    time: '2023-03-07',
  },
  {
    id: 3,
    orderID: 'JJD10N17',
    to: 'Beijing, China',
    toImg: require('../assets/images/china.png'),
    from: 'Cape Town, RSA',
    fromImg: require('../assets/images/south-africa.png'),
    type: 'RFF',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Ocean Freight',
    image: require('../assets/images/water.png'),
    status: 'Delivery Update',
    time: '2023-04-11',
  },
  {
    id: 4,
    orderID: 'MDJ7163S',
    to: 'Lagos, Nigeria',
    toImg: require('../assets/images/nigeria.png'),
    from: 'Ibadan, Nigeria',
    fromImg: require('../assets/images/nigeria.png'),
    type: 'RFQ',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Canceled',
    time: '2023-03-22',
  },
  {
    id: 5,
    orderID: 'NCI20CNA',
    to: 'Algiers, Algeria',
    toImg: require('../assets/images/algeria.png'),
    from: 'Kinshasa, DRC',
    fromImg: require('../assets/images/drc.png'),
    type: 'RFF',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Request for Review',
    time: '2023-05-18',
  },
  {
    id: 6,
    orderID: 'CNCO22O',
    to: 'Sao Paulo, Brazil',
    toImg: require('../assets/images/brazil.png'),
    from: 'Seoul, South Korea',
    fromImg: require('../assets/images/south-korea.png'),
    type: 'RFQ',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for atleast 1 year.',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Completed',
    time: '2023-04-13',
  },
];

const replyList = [
  {
    id: 0,
    supplier: 'Green Food',
    name: 'Tomato Crushed Tomatoes',
    businessType: 'Wholesale',
    cert: 'SON, NAFDAC, ISO900',
    description:
      'We source out tomato products and ingredients from top producers across the globe. Our tomato product suppliers guarantee excellent manufacturing practices and quality products in strategic locations around the world such as Europe, the United States, and South America. Our specific value to your organization comes from our expertise in logistics combined with our excellent relationships with the best partners and bulk suppliers. These supply chain essentials ensure you the best quality and price value for your Sellers tomato product needs. Tomato Products Tomato Paste bulk tomato paste Wholesale tomato paste is an essential ingredient in many food product and restaurant offerings. Rich tomato flavor is key to stimulating the taste buds and accentuating the savory notes of your product.',
    overview:
      'it is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.',
    rating: 4.0,
    distance: 2.5,
    address: 'Plot 4, 611 Road, Off 7th Avenue',
    address2: 'Jos, NIigeria',
    country: 'Nigeria',
    city: 'Jos',
    qty: 'MOQ: 1 Tons (UK)',
    sample: 'Available, sample cost by supplier',
    expiry: '14, April, 2024',
    paymentMethod: 'Advance Payment',
    expiryDays: 14,
    supplyAbility: '25000 Tonnes/week',
    minOrder: '15 Tonnes',
    orderID: 'CNCO22O',
    orderType: 'RFF',
    qtyOffered: 140,
    paymentType: 'Advanced Payment',
    deliveryDuration: 20,
    price: 3000000,
    usdPrice: 3000,
    latitude: 4.92805,
    longitude: 8.32705,
    buyFrequency: 'Once',
    estRevenue: 390000000,
    service: 'Domestic',
    totalStaff: 300,
    responseTime: '1 hour',
    containerCount: 7,
    containerSize: 40,
    ordersCompleted: 410,
    storeImg: require('../assets/images/res6.png'),
    storeBanner: require('../assets/images/store1.jpg'),
    image: require('../assets/images/tomatoes.png'),
  },
  {
    id: 1,
    supplier: 'Tona P',
    name: 'Fresh Apples',
    businessType: 'Large Retail',
    cert: 'SON, NAFDAC',
    description:
      'We source out tomato products and ingredients from top producers across the globe. Our tomato product suppliers guarantee excellent manufacturing practices and quality products in strategic locations around the world such as Europe, the United States, and South America. Our specific value to your organization comes from our expertise in logistics combined with our excellent relationships with the best partners and bulk suppliers. These supply chain essentials ensure you the best quality and price value for your Sellers tomato product needs. Tomato Products Tomato Paste bulk tomato paste Wholesale tomato paste is an essential ingredient in many food product and restaurant offerings. Rich tomato flavor is key to stimulating the taste buds and accentuating the savory notes of your product.',
    overview:
      'it is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.',
    rating: 4.5,
    distance: 4,
    country: 'Ghana',
    city: 'Kumasi',
    address: 'Plot 4, 611 Road, Off 7th Avenue',
    address2: 'Kumasi, Ghana',
    qty: 'MOQ: 1 Tons (UK)',
    sample: 'Available, sample cost by supplier',
    expiry: '8, June, 2024',
    expiryDays: 21,
    supplyAbility: '15000 Tonnes/week',
    minOrder: '5 Tonnes',
    orderID: 'MDJ7163S',
    doc: 'product-spec.pdf',
    orderType: 'RFQ',
    price: 1000000,
    usdPrice: 10000,
    latitude: 4.92805,
    longitude: 8.32705,
    buyFrequency: 'Twice',
    estRevenue: 40000000,
    qtyOffered: 200,
    paymentType: 'Advanced Payment',
    paymentMethod: 'Advance Payment',
    deliveryDuration: 30,
    service: 'International',
    totalStaff: 130,
    responseTime: '40 Minutes',
    containerCount: 4,
    containerSize: 60,
    ordersCompleted: 40,
    storeImg: require('../assets/images/res1.png'),
    storeBanner: require('../assets/images/store2.jpg'),
    image: require('../assets/images/apple.png'),
  },
];

const shipStatusInfo_OrderReceived = [
  {
    id: 1,
    orderType: 'International',
    orderTypeImg: require('../assets/images/international.png'),
    orderTypeDesc: 'Serving international delivery',
    order: replyList[1],
    name: 'Bonoze Catering Services',
    address:
      'No. 38, S.L Akintola Blvd, Garki II, Abuja, 900108, Graki 2, Federal Capital Territory, Nigeria',
  },
];

const shipStatusInfo_OrderAccepted = [
  {
    id: 1,
    orderID: 'BC5678XX',
  },
];

const shipStatusInfo_OrderStarted = [
  {
    id: 1,
    orderID: 'BC5678XX',
    info: 'Your Expected Delivery Date is 10 - 15th June, 2023',
  },
];

const shipStatusInfo_OrderArrived = [
  {
    id: 1,
    trackID: '#TRC90182YUIA',
    info: 'Your date of delivery was updated to 10 - 15th June, 2023',
  },
];

const shipStatusInfo_OrderReviewRequest = [
  {
    id: 1,
    trackID: '90182YUIA',
    info: 'You have accepted Tomato King’s request to review your order and extend the delivery date.',
    duration: '4 days',
  },
];

const shipStatusInfo_OrderComplete = [
  {
    id: 1,
    trackID: '90182YUIA',
    info: replyList[1],
    recipient: 'Abu Bakar',
  },
];

const shipStatusInfo_OrderCanceled = [
  {
    id: 1,
    trackID: '#TRC90182YUIA',
    info: 'Your Order was Canceled',
  },
];

const shipStatusInfo_Payment = [
  {
    id: 1,
    paymentTerm: 'Advanced Payment',
    paymentMethod: 'Citibank Nigeria Ltd.',
    paymentBankImg: require('../assets/images/international.png'),
    totalItems: 2,
    amt: 919000,
    subTotal: 150000,
    discount: 5,
    total: 10690000,
  },
];

const shipping_status = [
  {
    id: 0,
    label: 'Order Received',
    date_time: '23rd September 2023, 11:00 AM',
    info: shipStatusInfo_OrderReceived,
    detail: 'View Details',
    is_current_status: false,
  },
  {
    id: 1,
    label: 'Order Accepted',
    date_time: '23rd September 2023, 11:00 AM',
    info: shipStatusInfo_OrderAccepted,
    detail: 'View Details',
    is_current_status: false,
  },
  {
    id: 2,
    label: 'Payment',
    date_time: '23rd September 2023, 11:00 AM',
    info: shipStatusInfo_Payment,
    detail: 'View Details',
    is_current_status: false,
  },
  {
    id: 3,
    label: 'Order Started',
    date_time: '23rd September 2023, 11:00 AM',
    info: shipStatusInfo_OrderStarted,
    detail: 'View Details',
    is_current_status: true,
  },
  {
    id: 4,
    label: 'Order Arrived',
    date_time: '',
    info: shipStatusInfo_OrderArrived,
    detail: 'View Details',
    is_current_status: false,
  },
  {
    id: 5,
    label: 'Order Review Request',
    date_time: '',
    info: shipStatusInfo_OrderReviewRequest,
    detail: 'View Details',
    is_current_status: false,
  },
  {
    id: 6,
    label: 'Order Complete',
    date_time: '',
    info: shipStatusInfo_OrderComplete,
    detail: 'View Details',
    is_current_status: false,
  },
  {
    id: 6,
    label: 'Order Canceled',
    date_time: '',
    info: shipStatusInfo_OrderCanceled,
    detail: 'View Details',
    is_current_status: false,
  },
];

const shipIcons = [
  {
    id: 0,
    image: require('../assets/icons/receive.png'),
  },
  {
    id: 1,
    image: require('../assets/icons/accepted.png'),
  },
  {
    id: 2,
    image: require('../assets/icons/payment.png'),
  },
  {
    id: 3,
    image: require('../assets/icons/started.png'),
  },
  {
    id: 4,
    image: require('../assets/icons/arrive.png'),
  },
  {
    id: 5,
    image: require('../assets/icons/review.png'),
  },
  {
    id: 6,
    image: require('../assets/icons/complete.png'),
  },
];

const transactionHistory = [
  {
    id: '10CS1203',
    title: 'Topped up wallet',
    status: 'CREDIT',
    amount: 405.23,
    date: '5 February, 2023',
  },
  {
    id: '019SJL83',
    title: 'Trip deduction',
    status: 'CREDIT',
    amount: 1519.5,
    date: '5 February, 2023',
  },
  {
    id: 'AB1293KS',
    title: 'Withdraw from your account',
    status: 'DEBIT',
    amount: 7000.1,
    date: '1 March, 2023',
  },
  {
    id: '203NV270',
    title: 'Added to wallet',
    status: 'CREDIT',
    amount: 914.4,
    date: '1 March, 2023',
  },
  {
    id: 'NU71NS1',
    title: 'Withdraw from wallet',
    status: 'DEBIT',
    amount: 527.26,
    date: '1 March, 2023',
  },
  {
    id: 'JD29824H',
    title: 'Land Deposit from bank',
    status: 'DEBIT',
    amount: 1240.142,
    date: '12 April, 2023',
  },
  {
    id: 'JDJ2902S',
    title: 'Simple RFF',
    status: 'CREDIT',
    amount: 31042.41,
    date: '12 April, 2023',
  },
  {
    id: 'XJA10311',
    title: 'Bill payment',
    status: 'DEBIT',
    amount: 23901.16,
    date: '05 May, 2023',
  },
  {
    id: 'MN791SK',
    title: 'Money Transfer',
    status: 'CREDIT',
    amount: 10000.0,
    date: '05 May, 2023',
  },
  {
    id: 'U82S01A',
    title: 'Wallet credit',
    status: 'CREDIT',
    amount: 401399.26,
    date: '12 June, 2023',
  },
  {
    id: 'TEU8134D',
    title: 'Data recharge',
    status: 'DEBIT',
    amount: 5400.48,
    date: '12 June, 2023',
  },
];

const rfqItems = [
  {
    id: 1,
    rfqNo: 'BC5678XX',
    to: 'Tokyo, Japan',
    toImg: require('../assets/images/japan.png'),
    departDate: '7 April, 2024',
    arrivalDate: '14, April, 2024',
    type: 'RFQ',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'International',
    image: require('../assets/images/land.png'),
    status: 'Order Arrived',
    expiry: 15,
    expiryDate: '05 September 2023',
    productName: 'Fresh Tomatoes',
    qty: 200,
    price: 5000000,
    orderID: 'JDN82020',
    incoterms: 'Free on Board (FOB)',
    paymentTerms: 'Advance Payment',
    productInfo: replyList[1],
  },
  {
    id: 2,
    rfqNo: 'DU1JO284',
    to: 'New York, USA',
    toImg: require('../assets/images/united-states.png'),
    departDate: '13 May, 2024',
    arrivalDate: '21, June, 2024',
    type: 'RFQ',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Air Freight',
    image: require('../assets/images/air.png'),
    status: 'Order Started',
    expiry: 15,
    expiryDate: '11 June 2023',
    productName: 'Apple',
    qty: 150,
    price: 5000000,
    orderID: 'ADJANV2',
    incoterms: 'Free on Board (FOB)',
    paymentTerms: 'Advance Payment',
    productInfo: replyList[1],
  },
  {
    id: 3,
    rfqNo: 'JJD10N17',
    to: 'Beijing, China',
    toImg: require('../assets/images/china.png'),
    departDate: '27 February, 2024',
    arrivalDate: '14, March, 2024',
    type: 'RFQ',
    desc: 'Title: I’m looking fresh tomatoes for frequent supply for at least 1 year.',
    serviceType: 'Ocean Freight',
    image: require('../assets/images/water.png'),
    status: 'Delivery Update',
    expiry: 15,
    expiryDate: '19 April 2023',
    productName: 'Yams',
    qty: 350,
    price: 5000000,
    orderID: 'CNVHB52',
    incoterms: 'Free on Board (FOB)',
    paymentTerms: 'Advance Payment',
    productInfo: replyList[1],
  },
];

const rffItems = [
  {
    id: 1,
    orderID: 'BC5678XX',
    to: 'Tokyo, Japan',
    toImg: require('../assets/images/japan.png'),
    departDate: '13 July, 2024',
    arrivalDate: '04, August, 2024',
    name: 'Toptal Limited',
    departAddress:
      'No. 38, S.L Akintola Blvd, Garki II, Abuja, 900108, Graki 2, Federal Capital Territory, Nigeria',
    arrivalAddress:
      'Wuse II, Abuja, AMAC, FCT. Kampala St. 900288, Wuse II, Abuja',
    from: 'Jos, Nigeria',
    fromImg: require('../assets/images/nigeria.png'),
    type: 'RFF',
    packageType: 'Box/Crate',
    transportMode: 'Land',
    relatedServices: 'Insurance, CC, IS, Cert.',
    portOrigin: 'Shangahi, China',
    portDestination: 'Lagos, Nigeria',
    productInfo: replyList[0],
  },
  {
    id: 2,
    orderID: 'DU1JO284',
    to: 'New York, USA',
    departDate: '7 April, 2024',
    arrivalDate: '14, April, 2024',
    toImg: require('../assets/images/united-states.png'),
    name: 'ABC Services',
    departAddress:
      'No. 38, S.L Akintola Blvd, Garki II, Abuja, 900108, Graki 2, Federal Capital Territory, Nigeria',
    arrivalAddress:
      'Wuse II, Abuja, AMAC, FCT. Kampala St. 900288, Wuse II, Abuja',
    from: 'Accra, Ghana',
    fromImg: require('../assets/images/ghana.png'),
    type: 'RFF',
    packageType: 'Box/Crate',
    transportMode: 'Land',
    relatedServices: 'Insurance, CC, IS, Cert.',
    portOrigin: 'Shangahi, China',
    portDestination: 'Lagos, Nigeria',
    productInfo: replyList[0],
  },
  {
    id: 3,
    orderID: 'JJD10N17',
    to: 'Beijing, China',
    departDate: '01 October, 2024',
    arrivalDate: '20, October, 2024',
    toImg: require('../assets/images/china.png'),
    name: 'Bonoze Catering Services',
    departAddress:
      'No. 38, S.L Akintola Blvd, Garki II, Abuja, 900108, Graki 2, Federal Capital Territory, Nigeria',
    arrivalAddress:
      'Wuse II, Abuja, AMAC, FCT. Kampala St. 900288, Wuse II, Abuja',
    from: 'Cape Town, RSA',
    fromImg: require('../assets/images/south-africa.png'),
    type: 'RFF',
    packageType: 'Box/Crate',
    transportMode: 'Air',
    relatedServices: 'Insurance, CC, IS, Cert.',
    portOrigin: 'Shangahi, China',
    portDestination: 'Lagos, Nigeria',
    productInfo: replyList[0],
  },
];

const rffAgentReq = [
  {
    id: 1,
    to: 'Tokyo, Japan freight forwarder seeks agents in ',
    toImg: require('../assets/images/japan.png'),
    from: 'Jos, Nigeria',
    fromImg: require('../assets/images/nigeria.png'),
    transportMode: 'Land',
    posted: '19 April 2023',
    for: 'Co-operation',
    status: 'Live',
  },
  {
    id: 2,
    to: 'New York, USA freight forwarder seeks agents in ',
    toImg: require('../assets/images/united-states.png'),
    from: 'Accra, Ghana',
    fromImg: require('../assets/images/ghana.png'),
    transportMode: 'Land',
    posted: '19 April 2023',
    for: 'Co-operation',
    portDestination: 'Lagos, Nigeria',
  },
  {
    id: 3,
    to: 'Beijing, China freight forwarder seeks agents in',
    toImg: require('../assets/images/china.png'),
    from: 'Cape Town, RSA',
    fromImg: require('../assets/images/south-africa.png'),
    transportMode: 'Land',
    posted: '19 April 2023',
    for: 'Co-operation',
    status: 'Live',
  },
];

const sellPendingOrders = [
  {
    id: 0,
    orderID: 'JAI8824',
    to: 'Munich, Germany',
    toImg: require('../assets/images/germany.png'),
    type: 'RFQ',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'RFQ Replies Sent',
    incoterms: 'Free on Board (FOB)',
    time: '2023-04-13',
    productInfo: replyList[1],
  },
  {
    id: 20,
    orderID: 'VAD892R',
    to: 'Cape Town, RSA',
    toImg: require('../assets/images/south-africa.png'),
    type: 'RFQ',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'International',
    image: require('../assets/images/air.png'),
    status: 'RFQ Replies Sent',
    incoterms: 'Free on Board (FOB)',
    time: '2023-04-13',
    productInfo: replyList[0],
  },
  {
    id: 14,
    orderID: '2JVN020',
    to: 'Accra, Ghana',
    toImg: require('../assets/images/ghana.png'),
    type: 'RFF',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'RFF Replies Sent',
    incoterms: 'Free on Board (FOB)',
    time: '2023-04-13',
    productInfo: replyList[1],
  },
  {
    id: 10,
    orderID: 'JAI8824',
    to: 'Abuja, Nigeria',
    toImg: require('../assets/images/nigeria.png'),
    type: 'RFF',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'RFF Replies Sent',
    incoterms: 'Free on Board (FOB)',
    time: '2023-04-13',
    productInfo: replyList[0],
  },
];

const seller_orders = [
  {
    id: 10,
    orderID: 'JAI8824',
    to: 'Abuja, Nigeria',
    toImg: require('../assets/images/nigeria.png'),
    type: 'RFQ',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Order Accepted',
    time: '2023-04-13',
  },
  {
    id: 9,
    orderID: 'JAI8824',
    to: 'Mumbai, India',
    toImg: require('../assets/images/india.png'),
    type: 'RFQ',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Order Completed',
    time: '2023-04-13',
  },
  {
    id: 7,
    orderID: 'DJ084N1',
    to: 'Kingston, Jamaica',
    toImg: require('../assets/images/jamaica.png'),
    type: 'RFF',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Order Delivered',
    time: '2023-02-10',
  },
  {
    id: 8,
    orderID: 'JDU290DK',
    to: 'Cairo, Egypt',
    toImg: require('../assets/images/egypt.png'),
    type: 'RFF',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Land',
    image: require('../assets/images/land.png'),
    status: 'Buyer Requested for Review',
    time: '2023-02-20',
  },
  {
    id: 1,
    orderID: 'BC5678XX',
    to: 'Tokyo, Japan',
    toImg: require('../assets/images/japan.png'),
    type: 'RFF',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'International',
    image: require('../assets/images/land.png'),
    status: 'Order Canceled',
    time: '2023-02-25',
  },
  {
    id: 2,
    orderID: 'DU1JO284',
    to: 'New York, USA',
    toImg: require('../assets/images/united-states.png'),
    type: 'RFQ',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Air Freight',
    image: require('../assets/images/air.png'),
    status: 'Order Accepted',
    time: '2023-03-07',
  },
  {
    id: 3,
    orderID: 'JJD10N17',
    to: 'Beijing, China',
    toImg: require('../assets/images/china.png'),
    type: 'RFF',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Ocean Freight',
    image: require('../assets/images/water.png'),
    status: 'Order Delivered',
    time: '2023-04-11',
  },
  {
    id: 4,
    orderID: 'MDJ7163S',
    to: 'Lagos, Nigeria',
    toImg: require('../assets/images/nigeria.png'),
    from: 'Ibadan, Nigeria',
    fromImg: require('../assets/images/nigeria.png'),
    type: 'RFQ',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Order Canceled',
    time: '2023-03-22',
  },
  {
    id: 5,
    orderID: 'NCI20CNA',
    to: 'Algiers, Algeria',
    toImg: require('../assets/images/algeria.png'),
    type: 'RFF',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Buyer Requested for Review',
    time: '2023-05-18',
  },
  {
    id: 6,
    orderID: 'CNCO22O',
    to: 'Sao Paulo, Brazil',
    toImg: require('../assets/images/brazil.png'),
    type: 'RFQ',
    desc: 'We need 50 bags of paddy rice',
    serviceType: 'Domestic',
    image: require('../assets/images/land.png'),
    status: 'Order Completed',
    time: '2023-04-13',
  },
];

export default {
  rffAgentReq,
  rffItems,
  rfqItems,
  stores,
  shipping_status,
  storeProducts,
  transactionHistory,
  reviews,
  promos,
  orders,
  myProfile,
  shipIcons,
  sellerProfile,
  seller_orders,
  notifications,
  replyList,
  sellPendingOrders,
};
