/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://4iihkv5r6fanhmumcpoutxupgq.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mk4s5vuqffcoljstmul6ksijna",
    "aws_cognito_identity_pool_id": "eu-west-1:d96634fa-7cd7-4ab9-9a3d-46621de86e25",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_61k9j887Z",
    "aws_user_pools_web_client_id": "ppjr0m5puo18vj5062ju4bcps",
    "oauth": {
        "domain": "tradelyx6020b379-6020b379-staging.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "tradelyx://",
        "redirectSignOut": "tradelyx://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "PHONE_NUMBER",
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "tradelyx-media150432-staging",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
