/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://wkfdea3hqnc5lknlhtwtrjr5oy.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-olimf7zinneethu6hxxxr4mgwe",
    "aws_cognito_identity_pool_id": "eu-west-1:e98bd842-72cb-4743-9248-b3e4ba919f60",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_PoJkp1ySP",
    "aws_user_pools_web_client_id": "3ms40opm94l93aa4gaa7qpk5ju",
    "oauth": {
        "domain": "tradelyx6020b379-6020b379-prod.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "tradelyx://",
        "redirectSignOut": "tradelyx://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "PHONE_NUMBER",
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "tradelyx-media215500-prod",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
