/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://faaeudd3wjhzfeaqmmkaikfuge.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fdcjw546d5d37kuu2psm5wcgl4",
    "aws_cognito_identity_pool_id": "eu-west-1:d901633e-b342-4bf6-b259-ecb0330f247e",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_SX0I8uvX9",
    "aws_user_pools_web_client_id": "52vrh8mh6d5t27mb0a31647q65",
    "oauth": {
        "domain": "tradelyx6020b379-6020b379-dev.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "tradelyx://",
        "redirectSignOut": "tradelyx://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "PHONE_NUMBER",
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "tradelyx-media212058-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
