/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

import * as APITypes from "../API";
type GeneratedSubscription<InputType, OutputType> = string & {
  __generatedSubscriptionInput: InputType;
  __generatedSubscriptionOutput: OutputType;
};

export const onCreateOrder = /* GraphQL */ `subscription OnCreateOrder($filter: ModelSubscriptionOrderFilterInput) {
  onCreateOrder(filter: $filter) {
    id
    createdAt
    SType
    requestID
    orderType
    orderStatus
    agreement
    toImage
    toCountry
    fromImage
    fromCountry
    replyMessage
    replies
    userID
    rfqID
    rffID
    sellOfferID
    productID
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateOrderSubscriptionVariables,
  APITypes.OnCreateOrderSubscription
>;
export const onUpdateOrder = /* GraphQL */ `subscription OnUpdateOrder($filter: ModelSubscriptionOrderFilterInput) {
  onUpdateOrder(filter: $filter) {
    id
    createdAt
    SType
    requestID
    orderType
    orderStatus
    agreement
    toImage
    toCountry
    fromImage
    fromCountry
    replyMessage
    replies
    userID
    rfqID
    rffID
    sellOfferID
    productID
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateOrderSubscriptionVariables,
  APITypes.OnUpdateOrderSubscription
>;
export const onDeleteOrder = /* GraphQL */ `subscription OnDeleteOrder($filter: ModelSubscriptionOrderFilterInput) {
  onDeleteOrder(filter: $filter) {
    id
    createdAt
    SType
    requestID
    orderType
    orderStatus
    agreement
    toImage
    toCountry
    fromImage
    fromCountry
    replyMessage
    replies
    userID
    rfqID
    rffID
    sellOfferID
    productID
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteOrderSubscriptionVariables,
  APITypes.OnDeleteOrderSubscription
>;
export const onCreateSellOffer = /* GraphQL */ `subscription OnCreateSellOffer($filter: ModelSubscriptionSellOfferFilterInput) {
  onCreateSellOffer(filter: $filter) {
    id
    createdAt
    SType
    sellOfferID
    requestCategory
    title
    tags
    productName
    description
    packageDesc
    image
    images
    rfqType
    packageType
    supplyCapacity
    placeOrigin
    landmark
    unit
    deliveryDate
    qtyMeasure
    basePrice
    fobPrice
    paymentType
    paymentMethod
    offerValidity
    userID
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateSellOfferSubscriptionVariables,
  APITypes.OnCreateSellOfferSubscription
>;
export const onUpdateSellOffer = /* GraphQL */ `subscription OnUpdateSellOffer($filter: ModelSubscriptionSellOfferFilterInput) {
  onUpdateSellOffer(filter: $filter) {
    id
    createdAt
    SType
    sellOfferID
    requestCategory
    title
    tags
    productName
    description
    packageDesc
    image
    images
    rfqType
    packageType
    supplyCapacity
    placeOrigin
    landmark
    unit
    deliveryDate
    qtyMeasure
    basePrice
    fobPrice
    paymentType
    paymentMethod
    offerValidity
    userID
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateSellOfferSubscriptionVariables,
  APITypes.OnUpdateSellOfferSubscription
>;
export const onDeleteSellOffer = /* GraphQL */ `subscription OnDeleteSellOffer($filter: ModelSubscriptionSellOfferFilterInput) {
  onDeleteSellOffer(filter: $filter) {
    id
    createdAt
    SType
    sellOfferID
    requestCategory
    title
    tags
    productName
    description
    packageDesc
    image
    images
    rfqType
    packageType
    supplyCapacity
    placeOrigin
    landmark
    unit
    deliveryDate
    qtyMeasure
    basePrice
    fobPrice
    paymentType
    paymentMethod
    offerValidity
    userID
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteSellOfferSubscriptionVariables,
  APITypes.OnDeleteSellOfferSubscription
>;
export const onCreateRFQ = /* GraphQL */ `subscription OnCreateRFQ($filter: ModelSubscriptionRFQFilterInput) {
  onCreateRFQ(filter: $filter) {
    id
    createdAt
    SType
    rfqNo
    rfqType
    title
    requestCategory
    description
    documents
    productName
    tags
    qty
    buyFrequency
    budget
    placeOrigin
    placeOriginFlag
    placeOriginName
    landmark
    unit
    incoterms
    placeDestinationName
    placeDestination
    placeDestinationFlag
    destinationCountry
    deliveryPeriod
    expiryDate
    paymentType
    paymentMethod
    userID
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateRFQSubscriptionVariables,
  APITypes.OnCreateRFQSubscription
>;
export const onUpdateRFQ = /* GraphQL */ `subscription OnUpdateRFQ($filter: ModelSubscriptionRFQFilterInput) {
  onUpdateRFQ(filter: $filter) {
    id
    createdAt
    SType
    rfqNo
    rfqType
    title
    requestCategory
    description
    documents
    productName
    tags
    qty
    buyFrequency
    budget
    placeOrigin
    placeOriginFlag
    placeOriginName
    landmark
    unit
    incoterms
    placeDestinationName
    placeDestination
    placeDestinationFlag
    destinationCountry
    deliveryPeriod
    expiryDate
    paymentType
    paymentMethod
    userID
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateRFQSubscriptionVariables,
  APITypes.OnUpdateRFQSubscription
>;
export const onDeleteRFQ = /* GraphQL */ `subscription OnDeleteRFQ($filter: ModelSubscriptionRFQFilterInput) {
  onDeleteRFQ(filter: $filter) {
    id
    createdAt
    SType
    rfqNo
    rfqType
    title
    requestCategory
    description
    documents
    productName
    tags
    qty
    buyFrequency
    budget
    placeOrigin
    placeOriginFlag
    placeOriginName
    landmark
    unit
    incoterms
    placeDestinationName
    placeDestination
    placeDestinationFlag
    destinationCountry
    deliveryPeriod
    expiryDate
    paymentType
    paymentMethod
    userID
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteRFQSubscriptionVariables,
  APITypes.OnDeleteRFQSubscription
>;
export const onCreateRFF = /* GraphQL */ `subscription OnCreateRFF($filter: ModelSubscriptionRFFFilterInput) {
  onCreateRFF(filter: $filter) {
    id
    createdAt
    SType
    rffNo
    rffType
    deliveryPeriod
    requestCategory
    rffRequestType
    productName
    handling
    budget
    loadDate
    weight
    qty
    length
    width
    height
    packageType
    placeOrigin
    placeOriginFlag
    placeOriginName
    placeDestinationName
    placeDestinationFlag
    destinationCountry
    placeDestination
    relatedServices
    document
    notes
    containerDetails
    containerSize
    containerType
    requestType
    userID
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateRFFSubscriptionVariables,
  APITypes.OnCreateRFFSubscription
>;
export const onUpdateRFF = /* GraphQL */ `subscription OnUpdateRFF($filter: ModelSubscriptionRFFFilterInput) {
  onUpdateRFF(filter: $filter) {
    id
    createdAt
    SType
    rffNo
    rffType
    deliveryPeriod
    requestCategory
    rffRequestType
    productName
    handling
    budget
    loadDate
    weight
    qty
    length
    width
    height
    packageType
    placeOrigin
    placeOriginFlag
    placeOriginName
    placeDestinationName
    placeDestinationFlag
    destinationCountry
    placeDestination
    relatedServices
    document
    notes
    containerDetails
    containerSize
    containerType
    requestType
    userID
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateRFFSubscriptionVariables,
  APITypes.OnUpdateRFFSubscription
>;
export const onDeleteRFF = /* GraphQL */ `subscription OnDeleteRFF($filter: ModelSubscriptionRFFFilterInput) {
  onDeleteRFF(filter: $filter) {
    id
    createdAt
    SType
    rffNo
    rffType
    deliveryPeriod
    requestCategory
    rffRequestType
    productName
    handling
    budget
    loadDate
    weight
    qty
    length
    width
    height
    packageType
    placeOrigin
    placeOriginFlag
    placeOriginName
    placeDestinationName
    placeDestinationFlag
    destinationCountry
    placeDestination
    relatedServices
    document
    notes
    containerDetails
    containerSize
    containerType
    requestType
    userID
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteRFFSubscriptionVariables,
  APITypes.OnDeleteRFFSubscription
>;
export const onCreateReview = /* GraphQL */ `subscription OnCreateReview($filter: ModelSubscriptionReviewFilterInput) {
  onCreateReview(filter: $filter) {
    id
    name
    rating
    comment
    forUserID
    userID
    productID
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateReviewSubscriptionVariables,
  APITypes.OnCreateReviewSubscription
>;
export const onUpdateReview = /* GraphQL */ `subscription OnUpdateReview($filter: ModelSubscriptionReviewFilterInput) {
  onUpdateReview(filter: $filter) {
    id
    name
    rating
    comment
    forUserID
    userID
    productID
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateReviewSubscriptionVariables,
  APITypes.OnUpdateReviewSubscription
>;
export const onDeleteReview = /* GraphQL */ `subscription OnDeleteReview($filter: ModelSubscriptionReviewFilterInput) {
  onDeleteReview(filter: $filter) {
    id
    name
    rating
    comment
    forUserID
    userID
    productID
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteReviewSubscriptionVariables,
  APITypes.OnDeleteReviewSubscription
>;
export const onCreateProduct = /* GraphQL */ `subscription OnCreateProduct($filter: ModelSubscriptionProductFilterInput) {
  onCreateProduct(filter: $filter) {
    id
    createdAt
    SType
    title
    productImage
    image
    images
    description
    productSpec
    rating
    tags
    productCert
    supplyCapacity
    minOrderQty
    packageType
    quantity
    transportMode
    placeOrigin
    dateAvailable
    productDocs
    productCertDocs
    category
    commodityCategory
    userID
    Reviews {
      items {
        id
        name
        rating
        comment
        forUserID
        userID
        productID
        createdAt
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateProductSubscriptionVariables,
  APITypes.OnCreateProductSubscription
>;
export const onUpdateProduct = /* GraphQL */ `subscription OnUpdateProduct($filter: ModelSubscriptionProductFilterInput) {
  onUpdateProduct(filter: $filter) {
    id
    createdAt
    SType
    title
    productImage
    image
    images
    description
    productSpec
    rating
    tags
    productCert
    supplyCapacity
    minOrderQty
    packageType
    quantity
    transportMode
    placeOrigin
    dateAvailable
    productDocs
    productCertDocs
    category
    commodityCategory
    userID
    Reviews {
      items {
        id
        name
        rating
        comment
        forUserID
        userID
        productID
        createdAt
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateProductSubscriptionVariables,
  APITypes.OnUpdateProductSubscription
>;
export const onDeleteProduct = /* GraphQL */ `subscription OnDeleteProduct($filter: ModelSubscriptionProductFilterInput) {
  onDeleteProduct(filter: $filter) {
    id
    createdAt
    SType
    title
    productImage
    image
    images
    description
    productSpec
    rating
    tags
    productCert
    supplyCapacity
    minOrderQty
    packageType
    quantity
    transportMode
    placeOrigin
    dateAvailable
    productDocs
    productCertDocs
    category
    commodityCategory
    userID
    Reviews {
      items {
        id
        name
        rating
        comment
        forUserID
        userID
        productID
        createdAt
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteProductSubscriptionVariables,
  APITypes.OnDeleteProductSubscription
>;
export const onCreateUser = /* GraphQL */ `subscription OnCreateUser($filter: ModelSubscriptionUserFilterInput) {
  onCreateUser(filter: $filter) {
    id
    name
    email
    phone_number
    rating
    accountType
    lat
    lng
    ledgerBalance
    address
    city
    state
    zipCode
    lga
    website
    incorporateDate
    rcNumber
    totalOrders
    level
    identification
    identificationNumber
    identityDocs
    keyProduct
    country
    inviteCode
    accountCategory
    title
    logo
    backgroundImage
    images
    businessType
    certifications
    certsDoc
    mainMarkets
    memberShipType
    sellerLevel
    estRevenue
    totalStaff
    responseTime
    languages
    legalRep
    overview
    activeOrder
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    Products {
      items {
        id
        createdAt
        SType
        title
        productImage
        image
        images
        description
        productSpec
        rating
        tags
        productCert
        supplyCapacity
        minOrderQty
        packageType
        quantity
        transportMode
        placeOrigin
        dateAvailable
        productDocs
        productCertDocs
        category
        commodityCategory
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    Reviews {
      items {
        id
        name
        rating
        comment
        forUserID
        userID
        productID
        createdAt
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    RFQS {
      items {
        id
        createdAt
        SType
        rfqNo
        rfqType
        title
        requestCategory
        description
        documents
        productName
        tags
        qty
        buyFrequency
        budget
        placeOrigin
        placeOriginFlag
        placeOriginName
        landmark
        unit
        incoterms
        placeDestinationName
        placeDestination
        placeDestinationFlag
        destinationCountry
        deliveryPeriod
        expiryDate
        paymentType
        paymentMethod
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    RFFS {
      items {
        id
        createdAt
        SType
        rffNo
        rffType
        deliveryPeriod
        requestCategory
        rffRequestType
        productName
        handling
        budget
        loadDate
        weight
        qty
        length
        width
        height
        packageType
        placeOrigin
        placeOriginFlag
        placeOriginName
        placeDestinationName
        placeDestinationFlag
        destinationCountry
        placeDestination
        relatedServices
        document
        notes
        containerDetails
        containerSize
        containerType
        requestType
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    SellOffers {
      items {
        id
        createdAt
        SType
        sellOfferID
        requestCategory
        title
        tags
        productName
        description
        packageDesc
        image
        images
        rfqType
        packageType
        supplyCapacity
        placeOrigin
        landmark
        unit
        deliveryDate
        qtyMeasure
        basePrice
        fobPrice
        paymentType
        paymentMethod
        offerValidity
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    Wishlists {
      items {
        id
        createdAt
        SType
        productImage
        title
        serviceType
        supplyCapacity
        minOrderQty
        fobPrice
        productID
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateUserSubscriptionVariables,
  APITypes.OnCreateUserSubscription
>;
export const onUpdateUser = /* GraphQL */ `subscription OnUpdateUser($filter: ModelSubscriptionUserFilterInput) {
  onUpdateUser(filter: $filter) {
    id
    name
    email
    phone_number
    rating
    accountType
    lat
    lng
    ledgerBalance
    address
    city
    state
    zipCode
    lga
    website
    incorporateDate
    rcNumber
    totalOrders
    level
    identification
    identificationNumber
    identityDocs
    keyProduct
    country
    inviteCode
    accountCategory
    title
    logo
    backgroundImage
    images
    businessType
    certifications
    certsDoc
    mainMarkets
    memberShipType
    sellerLevel
    estRevenue
    totalStaff
    responseTime
    languages
    legalRep
    overview
    activeOrder
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    Products {
      items {
        id
        createdAt
        SType
        title
        productImage
        image
        images
        description
        productSpec
        rating
        tags
        productCert
        supplyCapacity
        minOrderQty
        packageType
        quantity
        transportMode
        placeOrigin
        dateAvailable
        productDocs
        productCertDocs
        category
        commodityCategory
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    Reviews {
      items {
        id
        name
        rating
        comment
        forUserID
        userID
        productID
        createdAt
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    RFQS {
      items {
        id
        createdAt
        SType
        rfqNo
        rfqType
        title
        requestCategory
        description
        documents
        productName
        tags
        qty
        buyFrequency
        budget
        placeOrigin
        placeOriginFlag
        placeOriginName
        landmark
        unit
        incoterms
        placeDestinationName
        placeDestination
        placeDestinationFlag
        destinationCountry
        deliveryPeriod
        expiryDate
        paymentType
        paymentMethod
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    RFFS {
      items {
        id
        createdAt
        SType
        rffNo
        rffType
        deliveryPeriod
        requestCategory
        rffRequestType
        productName
        handling
        budget
        loadDate
        weight
        qty
        length
        width
        height
        packageType
        placeOrigin
        placeOriginFlag
        placeOriginName
        placeDestinationName
        placeDestinationFlag
        destinationCountry
        placeDestination
        relatedServices
        document
        notes
        containerDetails
        containerSize
        containerType
        requestType
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    SellOffers {
      items {
        id
        createdAt
        SType
        sellOfferID
        requestCategory
        title
        tags
        productName
        description
        packageDesc
        image
        images
        rfqType
        packageType
        supplyCapacity
        placeOrigin
        landmark
        unit
        deliveryDate
        qtyMeasure
        basePrice
        fobPrice
        paymentType
        paymentMethod
        offerValidity
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    Wishlists {
      items {
        id
        createdAt
        SType
        productImage
        title
        serviceType
        supplyCapacity
        minOrderQty
        fobPrice
        productID
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateUserSubscriptionVariables,
  APITypes.OnUpdateUserSubscription
>;
export const onDeleteUser = /* GraphQL */ `subscription OnDeleteUser($filter: ModelSubscriptionUserFilterInput) {
  onDeleteUser(filter: $filter) {
    id
    name
    email
    phone_number
    rating
    accountType
    lat
    lng
    ledgerBalance
    address
    city
    state
    zipCode
    lga
    website
    incorporateDate
    rcNumber
    totalOrders
    level
    identification
    identificationNumber
    identityDocs
    keyProduct
    country
    inviteCode
    accountCategory
    title
    logo
    backgroundImage
    images
    businessType
    certifications
    certsDoc
    mainMarkets
    memberShipType
    sellerLevel
    estRevenue
    totalStaff
    responseTime
    languages
    legalRep
    overview
    activeOrder
    Orders {
      items {
        id
        createdAt
        SType
        requestID
        orderType
        orderStatus
        agreement
        toImage
        toCountry
        fromImage
        fromCountry
        replyMessage
        replies
        userID
        rfqID
        rffID
        sellOfferID
        productID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    Products {
      items {
        id
        createdAt
        SType
        title
        productImage
        image
        images
        description
        productSpec
        rating
        tags
        productCert
        supplyCapacity
        minOrderQty
        packageType
        quantity
        transportMode
        placeOrigin
        dateAvailable
        productDocs
        productCertDocs
        category
        commodityCategory
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    Reviews {
      items {
        id
        name
        rating
        comment
        forUserID
        userID
        productID
        createdAt
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    RFQS {
      items {
        id
        createdAt
        SType
        rfqNo
        rfqType
        title
        requestCategory
        description
        documents
        productName
        tags
        qty
        buyFrequency
        budget
        placeOrigin
        placeOriginFlag
        placeOriginName
        landmark
        unit
        incoterms
        placeDestinationName
        placeDestination
        placeDestinationFlag
        destinationCountry
        deliveryPeriod
        expiryDate
        paymentType
        paymentMethod
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    RFFS {
      items {
        id
        createdAt
        SType
        rffNo
        rffType
        deliveryPeriod
        requestCategory
        rffRequestType
        productName
        handling
        budget
        loadDate
        weight
        qty
        length
        width
        height
        packageType
        placeOrigin
        placeOriginFlag
        placeOriginName
        placeDestinationName
        placeDestinationFlag
        destinationCountry
        placeDestination
        relatedServices
        document
        notes
        containerDetails
        containerSize
        containerType
        requestType
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    SellOffers {
      items {
        id
        createdAt
        SType
        sellOfferID
        requestCategory
        title
        tags
        productName
        description
        packageDesc
        image
        images
        rfqType
        packageType
        supplyCapacity
        placeOrigin
        landmark
        unit
        deliveryDate
        qtyMeasure
        basePrice
        fobPrice
        paymentType
        paymentMethod
        offerValidity
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    Wishlists {
      items {
        id
        createdAt
        SType
        productImage
        title
        serviceType
        supplyCapacity
        minOrderQty
        fobPrice
        productID
        userID
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteUserSubscriptionVariables,
  APITypes.OnDeleteUserSubscription
>;
export const onCreateWishlist = /* GraphQL */ `subscription OnCreateWishlist($filter: ModelSubscriptionWishlistFilterInput) {
  onCreateWishlist(filter: $filter) {
    id
    createdAt
    SType
    productImage
    title
    serviceType
    supplyCapacity
    minOrderQty
    fobPrice
    productID
    userID
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateWishlistSubscriptionVariables,
  APITypes.OnCreateWishlistSubscription
>;
export const onUpdateWishlist = /* GraphQL */ `subscription OnUpdateWishlist($filter: ModelSubscriptionWishlistFilterInput) {
  onUpdateWishlist(filter: $filter) {
    id
    createdAt
    SType
    productImage
    title
    serviceType
    supplyCapacity
    minOrderQty
    fobPrice
    productID
    userID
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateWishlistSubscriptionVariables,
  APITypes.OnUpdateWishlistSubscription
>;
export const onDeleteWishlist = /* GraphQL */ `subscription OnDeleteWishlist($filter: ModelSubscriptionWishlistFilterInput) {
  onDeleteWishlist(filter: $filter) {
    id
    createdAt
    SType
    productImage
    title
    serviceType
    supplyCapacity
    minOrderQty
    fobPrice
    productID
    userID
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteWishlistSubscriptionVariables,
  APITypes.OnDeleteWishlistSubscription
>;
